// <auto-generated />
using System;
using BeHealthy.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BeHealthy.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250209055049_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BeHealthy.Domain.Entities.AppSetting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Caption")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Group")
                        .HasColumnType("integer");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("AppSettings", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Caption = "Requires Room for Appointment",
                            Description = "Indicates if a room is required for an appointment.",
                            Group = 0,
                            Key = "AppointmentRequiresRoom",
                            Type = 0,
                            Value = "false"
                        },
                        new
                        {
                            Id = 2,
                            Caption = "Do not allow doctors without a specialty",
                            Description = "Indicates if doctors without a specialty should be allowed.",
                            Group = 2,
                            Key = "DoNotAllowDoctorWithoutSpecialty",
                            Type = 0,
                            Value = "false"
                        },
                        new
                        {
                            Id = 3,
                            Caption = "Department requires supervisor",
                            Description = "Indicates if a department requires a supervisor.",
                            Group = 1,
                            Key = "DepartmentRequiresSupervisor",
                            Type = 0,
                            Value = "false"
                        },
                        new
                        {
                            Id = 4,
                            Caption = "Default Department Supervision",
                            Description = "The default supervisor selection for departments.",
                            Group = 1,
                            Key = "DefaultDepartmentSupervison",
                            Type = 1,
                            Value = "0"
                        });
                });

            modelBuilder.Entity("BeHealthy.Domain.Entities.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("Address")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Gender")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("ApplicationUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "admin",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "3cf7d0af-61b6-4ea4-a485-de041fbaa240",
                            Email = "admin@gmail.com",
                            EmailConfirmed = false,
                            FirstName = "Admin",
                            LastName = "User",
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN@GMAIL.COM",
                            NormalizedUserName = "ADMIN@GMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEJPLfytSVE2KZsC0YvMivMMp7l62ciH9UvVz9o4LG33WUDCLpAZlk3x0RrqsKK2fsA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "4acd0f1b-faea-4b3d-9ca0-76675d5e361b",
                            TwoFactorEnabled = false,
                            UserName = "admin@gmail.com"
                        },
                        new
                        {
                            Id = "1f216f95-87f6-4303-9888-1a29d1ccfa3d",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "78c1679f-4018-4fef-9d25-b07c4ff7ef61",
                            Email = "doctor1@hospital.com",
                            EmailConfirmed = false,
                            FirstName = "DoctorFirstName1",
                            LastName = "DoctorLastName1",
                            LockoutEnabled = false,
                            NormalizedEmail = "DOCTOR1@HOSPITAL.COM",
                            NormalizedUserName = "DOCTOR1@HOSPITAL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEL3eQVUEcBeoU70Ahw9niZFLVeJdllLFOEkp0JgNo2lDvPi9WkXqshGP7v9l1slAQQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "57c23246-4841-42d7-95d1-150eaa4f14ba",
                            TwoFactorEnabled = false,
                            UserName = "doctor1@hospital.com"
                        },
                        new
                        {
                            Id = "16448dfc-91ea-49d5-887a-f2b8eb2c439f",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "e9b9f368-a6f5-4bde-9283-ec477f30ee25",
                            Email = "nurse1@hospital.com",
                            EmailConfirmed = false,
                            FirstName = "NurseFirstName1",
                            LastName = "NurseLastName1",
                            LockoutEnabled = false,
                            NormalizedEmail = "NURSE1@HOSPITAL.COM",
                            NormalizedUserName = "NURSE1@HOSPITAL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEJLMAS6W0DMEMfaqDRZ70rkXLEmF58WWr93o4WEvUZfK0Rk2/rIgLjFsHXKzgTNw3w==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "32b2e103-8e49-4582-982d-c5e4e3e7f406",
                            TwoFactorEnabled = false,
                            UserName = "nurse1@hospital.com"
                        },
                        new
                        {
                            Id = "2a4d9452-9913-46c9-ae49-f7d01771d782",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "f09fd650-f38d-4d42-98a5-fac3cb3b1860",
                            Email = "patient1@hospital.com",
                            EmailConfirmed = false,
                            FirstName = "PatientFirstName1",
                            LastName = "PatientLastName1",
                            LockoutEnabled = false,
                            NormalizedEmail = "PATIENT1@HOSPITAL.COM",
                            NormalizedUserName = "PATIENT1@HOSPITAL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAENBNHeqZ/JkIv+91YNGCwVyu8NPk7Dd9CI548cSWUKM9XDXpXbPVt/qgaKQ4B4cPxg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "08131fe8-a80d-4bac-9c8c-66ae112369b9",
                            TwoFactorEnabled = false,
                            UserName = "patient1@hospital.com"
                        },
                        new
                        {
                            Id = "9aa95f69-2b47-4ec3-aec3-ac023b0d26c9",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "7523fc52-9936-4478-bed9-2744e7523155",
                            Email = "doctor2@hospital.com",
                            EmailConfirmed = false,
                            FirstName = "DoctorFirstName2",
                            LastName = "DoctorLastName2",
                            LockoutEnabled = false,
                            NormalizedEmail = "DOCTOR2@HOSPITAL.COM",
                            NormalizedUserName = "DOCTOR2@HOSPITAL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAELZi3798+zoHiIo1QDfMNQabJFZ88sJmVaCoao2Bl+dipJd3nuz3zrxGgGO375xEqQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "108553b1-3ca4-4dd3-bb03-7ce21969247c",
                            TwoFactorEnabled = false,
                            UserName = "doctor2@hospital.com"
                        },
                        new
                        {
                            Id = "007db76f-2b01-4538-b901-68c74fc81346",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "7c7ea8b4-462d-4e1f-89fe-c5d6289d3a45",
                            Email = "nurse2@hospital.com",
                            EmailConfirmed = false,
                            FirstName = "NurseFirstName2",
                            LastName = "NurseLastName2",
                            LockoutEnabled = false,
                            NormalizedEmail = "NURSE2@HOSPITAL.COM",
                            NormalizedUserName = "NURSE2@HOSPITAL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEJw46XHLHY/uYIv4Ns4RbbdTBqnnpJ5GvXLGJuRo2EMbd8O3l8nvfXlgf51GRfm3QA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "0cf33421-37a8-444b-9e19-2065d8216430",
                            TwoFactorEnabled = false,
                            UserName = "nurse2@hospital.com"
                        },
                        new
                        {
                            Id = "a8efe163-211c-422f-b11e-789ad05b6621",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "e858992e-1491-44b7-818f-155ae2c38295",
                            Email = "patient2@hospital.com",
                            EmailConfirmed = false,
                            FirstName = "PatientFirstName2",
                            LastName = "PatientLastName2",
                            LockoutEnabled = false,
                            NormalizedEmail = "PATIENT2@HOSPITAL.COM",
                            NormalizedUserName = "PATIENT2@HOSPITAL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEJieuadtJdhDqsJ7LJGb20g2QkS9UHTVJUJLGEmk7Y0mrwOVqmrEE2TVxHQhZ60i8g==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "b6672154-5e59-4a83-b63e-b58a07832c33",
                            TwoFactorEnabled = false,
                            UserName = "patient2@hospital.com"
                        },
                        new
                        {
                            Id = "0841d3b7-b31a-4b90-a94b-263235a54766",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "a5fc8af0-082d-4749-a582-2441fd2dc7de",
                            Email = "doctor3@hospital.com",
                            EmailConfirmed = false,
                            FirstName = "DoctorFirstName3",
                            LastName = "DoctorLastName3",
                            LockoutEnabled = false,
                            NormalizedEmail = "DOCTOR3@HOSPITAL.COM",
                            NormalizedUserName = "DOCTOR3@HOSPITAL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEHS1MOngsRTHTiXrD0WNtQ652DEyKdw2dEV3jdlALdbephjjNoR2JsARrEYVn3QmEA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "cbf4fb64-3179-47c0-8985-9a8bb86dfd52",
                            TwoFactorEnabled = false,
                            UserName = "doctor3@hospital.com"
                        },
                        new
                        {
                            Id = "99f2b23d-6103-4bae-8b4c-d561edf2d2c2",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "d718037c-159d-40be-ab29-52b0eef6b25b",
                            Email = "nurse3@hospital.com",
                            EmailConfirmed = false,
                            FirstName = "NurseFirstName3",
                            LastName = "NurseLastName3",
                            LockoutEnabled = false,
                            NormalizedEmail = "NURSE3@HOSPITAL.COM",
                            NormalizedUserName = "NURSE3@HOSPITAL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEJ4CxCKrYvCZTfjmXmDnuopTv4loVQ3Ip3ORQLS7WTXZhYLaxdII7QkGsD5A6dQ7/Q==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "895bd43d-bce3-4b7f-8fd0-27d49496f161",
                            TwoFactorEnabled = false,
                            UserName = "nurse3@hospital.com"
                        },
                        new
                        {
                            Id = "d9c24d72-8c57-4225-846a-9a7fc19afb0a",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "68555299-6680-4c33-b26a-f49dc5d468c5",
                            Email = "patient3@hospital.com",
                            EmailConfirmed = false,
                            FirstName = "PatientFirstName3",
                            LastName = "PatientLastName3",
                            LockoutEnabled = false,
                            NormalizedEmail = "PATIENT3@HOSPITAL.COM",
                            NormalizedUserName = "PATIENT3@HOSPITAL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEN6mqIDXkTlJJfHfFflyx64O3kef5EQ8hRJIudjiGoXyK5uh9jy/FmvTWU8h4DldUA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "3de711f2-6dad-44ae-9a09-17392f15682c",
                            TwoFactorEnabled = false,
                            UserName = "patient3@hospital.com"
                        },
                        new
                        {
                            Id = "24e3af45-92b4-4e72-803d-de91fc240340",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "f51fd366-a0d7-4564-9bae-45127c557c05",
                            Email = "doctor4@hospital.com",
                            EmailConfirmed = false,
                            FirstName = "DoctorFirstName4",
                            LastName = "DoctorLastName4",
                            LockoutEnabled = false,
                            NormalizedEmail = "DOCTOR4@HOSPITAL.COM",
                            NormalizedUserName = "DOCTOR4@HOSPITAL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEE62cgsaCuK2OVu+rmHgxmRz/NClajHaFBOgOincWfMX9j54Jq83wKPiN1MFBJX4WA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "45d43f81-185f-4b00-830f-4c05799d1a2a",
                            TwoFactorEnabled = false,
                            UserName = "doctor4@hospital.com"
                        },
                        new
                        {
                            Id = "e9fac186-5f4c-4de6-8ce5-fd17c6be365e",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "5376c650-c1fb-48a3-9985-c84ad1f949bc",
                            Email = "nurse4@hospital.com",
                            EmailConfirmed = false,
                            FirstName = "NurseFirstName4",
                            LastName = "NurseLastName4",
                            LockoutEnabled = false,
                            NormalizedEmail = "NURSE4@HOSPITAL.COM",
                            NormalizedUserName = "NURSE4@HOSPITAL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEA4C3Wbur6TDGgzb3kG2mGYmDr0XYY44k1o49Lbd7AW/6SXzUoFHuURzPqNeAbRrWA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "81de3a17-569c-43b5-bab6-d167d778eed5",
                            TwoFactorEnabled = false,
                            UserName = "nurse4@hospital.com"
                        },
                        new
                        {
                            Id = "33de060f-5ced-412e-bc2c-6d57ac6a0c39",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "ba594907-415a-4865-aec7-d8cd40a89f54",
                            Email = "patient4@hospital.com",
                            EmailConfirmed = false,
                            FirstName = "PatientFirstName4",
                            LastName = "PatientLastName4",
                            LockoutEnabled = false,
                            NormalizedEmail = "PATIENT4@HOSPITAL.COM",
                            NormalizedUserName = "PATIENT4@HOSPITAL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEM0eNxV+nqrUq1TnsT8BSoHv77bnRKRgiizDoi8xm8bdAyap+/gZzkHXy0zPGDQzkg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "01a93f3f-b2e8-44a7-aa82-739ef7d8d148",
                            TwoFactorEnabled = false,
                            UserName = "patient4@hospital.com"
                        },
                        new
                        {
                            Id = "b3eaac7f-00e4-48d4-a5c1-159c6a4158d6",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "181b77b7-6702-4dc8-9fcf-fc956bb3c94e",
                            Email = "doctor5@hospital.com",
                            EmailConfirmed = false,
                            FirstName = "DoctorFirstName5",
                            LastName = "DoctorLastName5",
                            LockoutEnabled = false,
                            NormalizedEmail = "DOCTOR5@HOSPITAL.COM",
                            NormalizedUserName = "DOCTOR5@HOSPITAL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEOqTH244e3uESImws8S40+H3Fvh4Kg8ObSB1N6MXXu0mL7JdQ3t2v9Oy8hjW1aaS0w==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "573bdaec-daa7-486d-9a29-0daa3eb5eff5",
                            TwoFactorEnabled = false,
                            UserName = "doctor5@hospital.com"
                        },
                        new
                        {
                            Id = "90f35c8d-b97f-41d4-9cf6-acf9eaf50a54",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "a4ff712b-f956-42cb-b8e7-8cad9d5dfe90",
                            Email = "nurse5@hospital.com",
                            EmailConfirmed = false,
                            FirstName = "NurseFirstName5",
                            LastName = "NurseLastName5",
                            LockoutEnabled = false,
                            NormalizedEmail = "NURSE5@HOSPITAL.COM",
                            NormalizedUserName = "NURSE5@HOSPITAL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEIJ2CKQFNIKtLt9iGAav5ZvjmRJ6hGvbdkmQr+ozjIKpFUk6whguVFj4STvWYsAlPg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "a07ab8b3-0378-4a66-a60e-1b9b5316e271",
                            TwoFactorEnabled = false,
                            UserName = "nurse5@hospital.com"
                        },
                        new
                        {
                            Id = "75a6b557-8dd2-4d67-b0a3-2692d458609c",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "604c9739-7130-4419-99c3-20c3777445f7",
                            Email = "patient5@hospital.com",
                            EmailConfirmed = false,
                            FirstName = "PatientFirstName5",
                            LastName = "PatientLastName5",
                            LockoutEnabled = false,
                            NormalizedEmail = "PATIENT5@HOSPITAL.COM",
                            NormalizedUserName = "PATIENT5@HOSPITAL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEIV0QHX1t4EKIy8G4ZNX8jzTyta7/GQsHFpOO1+Ar+InTtyy1xRLhfqgMY4HToHVDQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "1e2cc34f-a690-4987-903f-0a9695188390",
                            TwoFactorEnabled = false,
                            UserName = "patient5@hospital.com"
                        });
                });

            modelBuilder.Entity("BeHealthy.Domain.Entities.Appointment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AppointmentDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DoctorId")
                        .HasColumnType("integer");

                    b.Property<int>("Duration")
                        .HasColumnType("integer");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int?>("NurseId")
                        .HasColumnType("integer");

                    b.Property<int>("PatientId")
                        .HasColumnType("integer");

                    b.Property<int>("Reason")
                        .HasColumnType("integer");

                    b.Property<int?>("RoomId")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DoctorId");

                    b.HasIndex("NurseId");

                    b.HasIndex("PatientId");

                    b.HasIndex("RoomId");

                    b.ToTable("Appointments", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AppointmentDate = new DateTime(2025, 2, 4, 10, 0, 0, 0, DateTimeKind.Utc),
                            DoctorId = 1,
                            Duration = 60,
                            PatientId = 1,
                            Reason = 0,
                            Status = 1
                        },
                        new
                        {
                            Id = 2,
                            AppointmentDate = new DateTime(2025, 2, 6, 11, 0, 0, 0, DateTimeKind.Utc),
                            DoctorId = 2,
                            Duration = 60,
                            PatientId = 2,
                            Reason = 1,
                            Status = 2
                        },
                        new
                        {
                            Id = 3,
                            AppointmentDate = new DateTime(2025, 2, 7, 9, 0, 0, 0, DateTimeKind.Utc),
                            DoctorId = 3,
                            Duration = 60,
                            PatientId = 3,
                            Reason = 1,
                            Status = 2
                        },
                        new
                        {
                            Id = 4,
                            AppointmentDate = new DateTime(2025, 2, 8, 12, 0, 0, 0, DateTimeKind.Utc),
                            DoctorId = 4,
                            Duration = 60,
                            PatientId = 4,
                            Reason = 1,
                            Status = 1
                        },
                        new
                        {
                            Id = 5,
                            AppointmentDate = new DateTime(2025, 2, 9, 12, 0, 0, 0, DateTimeKind.Utc),
                            DoctorId = 3,
                            Duration = 60,
                            PatientId = 3,
                            Reason = 2,
                            Status = 0
                        },
                        new
                        {
                            Id = 6,
                            AppointmentDate = new DateTime(2025, 2, 9, 14, 0, 0, 0, DateTimeKind.Utc),
                            DoctorId = 4,
                            Duration = 60,
                            PatientId = 4,
                            Reason = 3,
                            Status = 3
                        },
                        new
                        {
                            Id = 7,
                            AppointmentDate = new DateTime(2025, 2, 9, 9, 0, 0, 0, DateTimeKind.Utc),
                            DoctorId = 4,
                            Duration = 60,
                            PatientId = 1,
                            Reason = 3,
                            Status = 0
                        },
                        new
                        {
                            Id = 8,
                            AppointmentDate = new DateTime(2025, 2, 9, 11, 0, 0, 0, DateTimeKind.Utc),
                            DoctorId = 3,
                            Duration = 60,
                            PatientId = 2,
                            Reason = 3,
                            Status = 0
                        },
                        new
                        {
                            Id = 9,
                            AppointmentDate = new DateTime(2025, 2, 9, 15, 0, 0, 0, DateTimeKind.Utc),
                            DoctorId = 1,
                            Duration = 60,
                            PatientId = 1,
                            Reason = 3,
                            Status = 3
                        },
                        new
                        {
                            Id = 10,
                            AppointmentDate = new DateTime(2025, 2, 10, 10, 0, 0, 0, DateTimeKind.Utc),
                            DoctorId = 5,
                            Duration = 60,
                            PatientId = 5,
                            Reason = 4,
                            Status = 0
                        },
                        new
                        {
                            Id = 11,
                            AppointmentDate = new DateTime(2025, 2, 11, 11, 0, 0, 0, DateTimeKind.Utc),
                            DoctorId = 1,
                            Duration = 60,
                            PatientId = 2,
                            Reason = 0,
                            Status = 3
                        },
                        new
                        {
                            Id = 12,
                            AppointmentDate = new DateTime(2025, 2, 12, 12, 0, 0, 0, DateTimeKind.Utc),
                            DoctorId = 2,
                            Duration = 60,
                            PatientId = 3,
                            Reason = 1,
                            Status = 0
                        },
                        new
                        {
                            Id = 13,
                            AppointmentDate = new DateTime(2025, 2, 19, 13, 0, 0, 0, DateTimeKind.Utc),
                            DoctorId = 4,
                            Duration = 60,
                            PatientId = 5,
                            Reason = 3,
                            Status = 0
                        },
                        new
                        {
                            Id = 14,
                            AppointmentDate = new DateTime(2025, 2, 24, 14, 0, 0, 0, DateTimeKind.Utc),
                            DoctorId = 5,
                            Duration = 60,
                            PatientId = 1,
                            Reason = 4,
                            Status = 3
                        });
                });

            modelBuilder.Entity("BeHealthy.Domain.Entities.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("HeadOfDepartmentId")
                        .HasColumnType("integer");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("HeadOfDepartmentId");

                    b.ToTable("Departments", (string)null);
                });

            modelBuilder.Entity("BeHealthy.Domain.Entities.Doctor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("DepartmentId")
                        .HasColumnType("integer");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Image")
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("SpecialtyId")
                        .HasColumnType("integer");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("SpecialtyId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Doctors", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 2, 9, 5, 50, 48, 577, DateTimeKind.Utc).AddTicks(5598),
                            FirstName = "DoctorFirstName1",
                            LastName = "DoctorLastName1",
                            UserId = "1f216f95-87f6-4303-9888-1a29d1ccfa3d"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 2, 9, 5, 50, 48, 768, DateTimeKind.Utc).AddTicks(6581),
                            FirstName = "DoctorFirstName2",
                            LastName = "DoctorLastName2",
                            UserId = "9aa95f69-2b47-4ec3-aec3-ac023b0d26c9"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 2, 9, 5, 50, 48, 963, DateTimeKind.Utc).AddTicks(26),
                            FirstName = "DoctorFirstName3",
                            LastName = "DoctorLastName3",
                            UserId = "0841d3b7-b31a-4b90-a94b-263235a54766"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2025, 2, 9, 5, 50, 49, 153, DateTimeKind.Utc).AddTicks(9264),
                            FirstName = "DoctorFirstName4",
                            LastName = "DoctorLastName4",
                            UserId = "24e3af45-92b4-4e72-803d-de91fc240340"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2025, 2, 9, 5, 50, 49, 343, DateTimeKind.Utc).AddTicks(42),
                            FirstName = "DoctorFirstName5",
                            LastName = "DoctorLastName5",
                            UserId = "b3eaac7f-00e4-48d4-a5c1-159c6a4158d6"
                        });
                });

            modelBuilder.Entity("BeHealthy.Domain.Entities.Nurse", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("DepartmentId")
                        .HasColumnType("integer");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Image")
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Nurses", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 2, 9, 5, 50, 48, 639, DateTimeKind.Utc).AddTicks(7767),
                            FirstName = "NurseFirstName1",
                            LastName = "NurseLastName1",
                            UserId = "16448dfc-91ea-49d5-887a-f2b8eb2c439f"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 2, 9, 5, 50, 48, 834, DateTimeKind.Utc).AddTicks(2715),
                            FirstName = "NurseFirstName2",
                            LastName = "NurseLastName2",
                            UserId = "007db76f-2b01-4538-b901-68c74fc81346"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 2, 9, 5, 50, 49, 28, DateTimeKind.Utc).AddTicks(2826),
                            FirstName = "NurseFirstName3",
                            LastName = "NurseLastName3",
                            UserId = "99f2b23d-6103-4bae-8b4c-d561edf2d2c2"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2025, 2, 9, 5, 50, 49, 218, DateTimeKind.Utc).AddTicks(346),
                            FirstName = "NurseFirstName4",
                            LastName = "NurseLastName4",
                            UserId = "e9fac186-5f4c-4de6-8ce5-fd17c6be365e"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2025, 2, 9, 5, 50, 49, 405, DateTimeKind.Utc).AddTicks(4219),
                            FirstName = "NurseFirstName5",
                            LastName = "NurseLastName5",
                            UserId = "90f35c8d-b97f-41d4-9cf6-acf9eaf50a54"
                        });
                });

            modelBuilder.Entity("BeHealthy.Domain.Entities.Patient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("DepartmentId")
                        .HasColumnType("integer");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Image")
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Patients", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 2, 9, 5, 50, 48, 703, DateTimeKind.Utc).AddTicks(4768),
                            FirstName = "PatientFirstName1",
                            LastName = "PatientLastName1",
                            UserId = "2a4d9452-9913-46c9-ae49-f7d01771d782"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 2, 9, 5, 50, 48, 899, DateTimeKind.Utc).AddTicks(1544),
                            FirstName = "PatientFirstName2",
                            LastName = "PatientLastName2",
                            UserId = "a8efe163-211c-422f-b11e-789ad05b6621"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 2, 9, 5, 50, 49, 91, DateTimeKind.Utc).AddTicks(2208),
                            FirstName = "PatientFirstName3",
                            LastName = "PatientLastName3",
                            UserId = "d9c24d72-8c57-4225-846a-9a7fc19afb0a"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2025, 2, 9, 5, 50, 49, 280, DateTimeKind.Utc).AddTicks(1272),
                            FirstName = "PatientFirstName4",
                            LastName = "PatientLastName4",
                            UserId = "33de060f-5ced-412e-bc2c-6d57ac6a0c39"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2025, 2, 9, 5, 50, 49, 467, DateTimeKind.Utc).AddTicks(26),
                            FirstName = "PatientFirstName5",
                            LastName = "PatientLastName5",
                            UserId = "75a6b557-8dd2-4d67-b0a3-2692d458609c"
                        });
                });

            modelBuilder.Entity("BeHealthy.Domain.Entities.Prescription", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DatePrescribed")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DoctorId")
                        .HasColumnType("integer");

                    b.Property<string>("Dosage")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Medication")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("PatientId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DoctorId");

                    b.HasIndex("PatientId");

                    b.ToTable("Prescriptions", (string)null);
                });

            modelBuilder.Entity("BeHealthy.Domain.Entities.Privilege", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Name")
                        .HasColumnType("integer");

                    b.Property<bool>("Value")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("Privileges");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = 0,
                            Value = false
                        },
                        new
                        {
                            Id = 2,
                            Name = 1,
                            Value = false
                        });
                });

            modelBuilder.Entity("BeHealthy.Domain.Entities.RolePrivilege", b =>
                {
                    b.Property<short>("Role")
                        .HasColumnType("smallint");

                    b.Property<int>("PrivilegeId")
                        .HasColumnType("integer");

                    b.HasKey("Role", "PrivilegeId");

                    b.HasIndex("PrivilegeId");

                    b.ToTable("RolePrivileges");

                    b.HasData(
                        new
                        {
                            Role = (short)2,
                            PrivilegeId = 1
                        },
                        new
                        {
                            Role = (short)2,
                            PrivilegeId = 2
                        },
                        new
                        {
                            Role = (short)4,
                            PrivilegeId = 1
                        },
                        new
                        {
                            Role = (short)4,
                            PrivilegeId = 2
                        },
                        new
                        {
                            Role = (short)3,
                            PrivilegeId = 1
                        },
                        new
                        {
                            Role = (short)3,
                            PrivilegeId = 2
                        });
                });

            modelBuilder.Entity("BeHealthy.Domain.Entities.Room", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Number")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.ToTable("Rooms", (string)null);
                });

            modelBuilder.Entity("BeHealthy.Domain.Entities.Specialty", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Specialities", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "0",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = "1",
                            Name = "Staff",
                            NormalizedName = "STAFF"
                        },
                        new
                        {
                            Id = "2",
                            Name = "Doctor",
                            NormalizedName = "DOCTOR"
                        },
                        new
                        {
                            Id = "3",
                            Name = "Nurse",
                            NormalizedName = "NURSE"
                        },
                        new
                        {
                            Id = "4",
                            Name = "Patient",
                            NormalizedName = "PATIENT"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "admin",
                            RoleId = "0"
                        },
                        new
                        {
                            UserId = "1f216f95-87f6-4303-9888-1a29d1ccfa3d",
                            RoleId = "2"
                        },
                        new
                        {
                            UserId = "16448dfc-91ea-49d5-887a-f2b8eb2c439f",
                            RoleId = "3"
                        },
                        new
                        {
                            UserId = "2a4d9452-9913-46c9-ae49-f7d01771d782",
                            RoleId = "3"
                        },
                        new
                        {
                            UserId = "9aa95f69-2b47-4ec3-aec3-ac023b0d26c9",
                            RoleId = "2"
                        },
                        new
                        {
                            UserId = "007db76f-2b01-4538-b901-68c74fc81346",
                            RoleId = "3"
                        },
                        new
                        {
                            UserId = "a8efe163-211c-422f-b11e-789ad05b6621",
                            RoleId = "3"
                        },
                        new
                        {
                            UserId = "0841d3b7-b31a-4b90-a94b-263235a54766",
                            RoleId = "2"
                        },
                        new
                        {
                            UserId = "99f2b23d-6103-4bae-8b4c-d561edf2d2c2",
                            RoleId = "3"
                        },
                        new
                        {
                            UserId = "d9c24d72-8c57-4225-846a-9a7fc19afb0a",
                            RoleId = "3"
                        },
                        new
                        {
                            UserId = "24e3af45-92b4-4e72-803d-de91fc240340",
                            RoleId = "2"
                        },
                        new
                        {
                            UserId = "e9fac186-5f4c-4de6-8ce5-fd17c6be365e",
                            RoleId = "3"
                        },
                        new
                        {
                            UserId = "33de060f-5ced-412e-bc2c-6d57ac6a0c39",
                            RoleId = "3"
                        },
                        new
                        {
                            UserId = "b3eaac7f-00e4-48d4-a5c1-159c6a4158d6",
                            RoleId = "2"
                        },
                        new
                        {
                            UserId = "90f35c8d-b97f-41d4-9cf6-acf9eaf50a54",
                            RoleId = "3"
                        },
                        new
                        {
                            UserId = "75a6b557-8dd2-4d67-b0a3-2692d458609c",
                            RoleId = "3"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("BeHealthy.Domain.Entities.Appointment", b =>
                {
                    b.HasOne("BeHealthy.Domain.Entities.Doctor", "Doctor")
                        .WithMany("Appointments")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BeHealthy.Domain.Entities.Nurse", "Nurse")
                        .WithMany("Appointments")
                        .HasForeignKey("NurseId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("BeHealthy.Domain.Entities.Patient", "Patient")
                        .WithMany("Appointments")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BeHealthy.Domain.Entities.Room", "Room")
                        .WithMany("Appointments")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Doctor");

                    b.Navigation("Nurse");

                    b.Navigation("Patient");

                    b.Navigation("Room");
                });

            modelBuilder.Entity("BeHealthy.Domain.Entities.Department", b =>
                {
                    b.HasOne("BeHealthy.Domain.Entities.Doctor", "HeadOfDepartment")
                        .WithMany()
                        .HasForeignKey("HeadOfDepartmentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("HeadOfDepartment");
                });

            modelBuilder.Entity("BeHealthy.Domain.Entities.Doctor", b =>
                {
                    b.HasOne("BeHealthy.Domain.Entities.Department", "Department")
                        .WithMany("Doctors")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("BeHealthy.Domain.Entities.Specialty", "Specialty")
                        .WithMany("Doctors")
                        .HasForeignKey("SpecialtyId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("BeHealthy.Domain.Entities.ApplicationUser", "User")
                        .WithOne("Doctor")
                        .HasForeignKey("BeHealthy.Domain.Entities.Doctor", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");

                    b.Navigation("Specialty");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BeHealthy.Domain.Entities.Nurse", b =>
                {
                    b.HasOne("BeHealthy.Domain.Entities.Department", "Department")
                        .WithMany("Nurses")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("BeHealthy.Domain.Entities.ApplicationUser", "User")
                        .WithOne("Nurse")
                        .HasForeignKey("BeHealthy.Domain.Entities.Nurse", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BeHealthy.Domain.Entities.Patient", b =>
                {
                    b.HasOne("BeHealthy.Domain.Entities.Department", "Department")
                        .WithMany("Patients")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("BeHealthy.Domain.Entities.ApplicationUser", "User")
                        .WithOne("Patient")
                        .HasForeignKey("BeHealthy.Domain.Entities.Patient", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BeHealthy.Domain.Entities.Prescription", b =>
                {
                    b.HasOne("BeHealthy.Domain.Entities.Doctor", "Doctor")
                        .WithMany()
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BeHealthy.Domain.Entities.Patient", "Patient")
                        .WithMany()
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Doctor");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("BeHealthy.Domain.Entities.RolePrivilege", b =>
                {
                    b.HasOne("BeHealthy.Domain.Entities.Privilege", "Privilege")
                        .WithMany("RolePrivileges")
                        .HasForeignKey("PrivilegeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Privilege");
                });

            modelBuilder.Entity("BeHealthy.Domain.Entities.Room", b =>
                {
                    b.HasOne("BeHealthy.Domain.Entities.Department", "Department")
                        .WithMany("Rooms")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("BeHealthy.Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("BeHealthy.Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BeHealthy.Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("BeHealthy.Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BeHealthy.Domain.Entities.ApplicationUser", b =>
                {
                    b.Navigation("Doctor");

                    b.Navigation("Nurse");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("BeHealthy.Domain.Entities.Department", b =>
                {
                    b.Navigation("Doctors");

                    b.Navigation("Nurses");

                    b.Navigation("Patients");

                    b.Navigation("Rooms");
                });

            modelBuilder.Entity("BeHealthy.Domain.Entities.Doctor", b =>
                {
                    b.Navigation("Appointments");
                });

            modelBuilder.Entity("BeHealthy.Domain.Entities.Nurse", b =>
                {
                    b.Navigation("Appointments");
                });

            modelBuilder.Entity("BeHealthy.Domain.Entities.Patient", b =>
                {
                    b.Navigation("Appointments");
                });

            modelBuilder.Entity("BeHealthy.Domain.Entities.Privilege", b =>
                {
                    b.Navigation("RolePrivileges");
                });

            modelBuilder.Entity("BeHealthy.Domain.Entities.Room", b =>
                {
                    b.Navigation("Appointments");
                });

            modelBuilder.Entity("BeHealthy.Domain.Entities.Specialty", b =>
                {
                    b.Navigation("Doctors");
                });
#pragma warning restore 612, 618
        }
    }
}
