// <auto-generated />
using System;
using BeHealthy.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BeHealthy.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BeHealthy.Domain.Entities.AppSetting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Caption")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Group")
                        .HasColumnType("integer");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("AppSettings", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Caption = "Requires Room for Appointment",
                            Description = "Indicates if a room is required for an appointment.",
                            Group = 0,
                            Key = "AppointmentRequiresRoom",
                            Type = 0,
                            Value = "false"
                        },
                        new
                        {
                            Id = 2,
                            Caption = "Do not allow doctors without a specialty",
                            Description = "Indicates if doctors without a specialty should be allowed.",
                            Group = 2,
                            Key = "DoNotAllowDoctorWithoutSpecialty",
                            Type = 0,
                            Value = "false"
                        },
                        new
                        {
                            Id = 3,
                            Caption = "Department requires supervisor",
                            Description = "Indicates if a department requires a supervisor.",
                            Group = 1,
                            Key = "DepartmentRequiresSupervisor",
                            Type = 0,
                            Value = "false"
                        },
                        new
                        {
                            Id = 4,
                            Caption = "Default Department Supervision",
                            Description = "The default supervisor selection for departments.",
                            Group = 1,
                            Key = "DefaultDepartmentSupervison",
                            Type = 1,
                            Value = "0"
                        });
                });

            modelBuilder.Entity("BeHealthy.Domain.Entities.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("Address")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Gender")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("ApplicationUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "admin",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "ad69c158-a638-455c-962a-813504e4f511",
                            Email = "admin@gmail.com",
                            EmailConfirmed = false,
                            FirstName = "Admin",
                            LastName = "User",
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN@GMAIL.COM",
                            NormalizedUserName = "ADMIN@GMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEPg95iyyIDjVYj8wRnjqPoBIiSHoqjCe+IloUIvqY6LmdJq9lSiLpketsg2+5xe9bA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "7494756f-89c4-4dfe-838e-1bf3b9237e34",
                            TwoFactorEnabled = false,
                            UserName = "admin@gmail.com"
                        },
                        new
                        {
                            Id = "de86fec1-42f2-4088-b643-1f708519ec41",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "aa283ea4-3544-4433-9cc6-6d6b3953c464",
                            Email = "doctor1@hospital.com",
                            EmailConfirmed = false,
                            FirstName = "DoctorFirstName1",
                            LastName = "DoctorLastName1",
                            LockoutEnabled = false,
                            NormalizedEmail = "DOCTOR1@HOSPITAL.COM",
                            NormalizedUserName = "DOCTOR1@HOSPITAL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEMTFZrhgmeSLN00ijXYi8JLbtn/00jJced5IZcg8azANRG52tpgqg3c6WBHz+i/Bog==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "12e12df2-abb1-484e-899c-78399d9f1963",
                            TwoFactorEnabled = false,
                            UserName = "doctor1@hospital.com"
                        },
                        new
                        {
                            Id = "04692c47-f89c-4fa8-ba2f-987f8519ee66",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "05fcc75a-1c93-41f4-8727-f276ba8e1cd0",
                            Email = "nurse1@hospital.com",
                            EmailConfirmed = false,
                            FirstName = "NurseFirstName1",
                            LastName = "NurseLastName1",
                            LockoutEnabled = false,
                            NormalizedEmail = "NURSE1@HOSPITAL.COM",
                            NormalizedUserName = "NURSE1@HOSPITAL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAELSFLW5TWNDFdOSCg0s2bzs6d6qRfcSuzvqCrvpJax8mf4AdrsorLJ52hGuDqhubiA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "592915b9-ae49-47e0-886a-58f1853ad0d1",
                            TwoFactorEnabled = false,
                            UserName = "nurse1@hospital.com"
                        },
                        new
                        {
                            Id = "686aa49c-ea4d-4c64-a51e-31fd4a94db5b",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "52ec8a4e-347d-41d5-869d-4d4bc0ccea97",
                            Email = "patient1@hospital.com",
                            EmailConfirmed = false,
                            FirstName = "PatientFirstName1",
                            LastName = "PatientLastName1",
                            LockoutEnabled = false,
                            NormalizedEmail = "PATIENT1@HOSPITAL.COM",
                            NormalizedUserName = "PATIENT1@HOSPITAL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEF8dlhHvlfkZ+XX+LvbPlYitb6274jZDargRdLn0GhDToN7FEBovakpMjBPmB352eA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "06b96988-adcb-4a8b-b919-78edfaea9fbd",
                            TwoFactorEnabled = false,
                            UserName = "patient1@hospital.com"
                        },
                        new
                        {
                            Id = "5fb0af0a-86f1-4059-9076-2eb2314e2099",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "0f53ccd1-9230-4c67-aa37-29afae762867",
                            Email = "doctor2@hospital.com",
                            EmailConfirmed = false,
                            FirstName = "DoctorFirstName2",
                            LastName = "DoctorLastName2",
                            LockoutEnabled = false,
                            NormalizedEmail = "DOCTOR2@HOSPITAL.COM",
                            NormalizedUserName = "DOCTOR2@HOSPITAL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEPkF2SvxHzMoQIq3UBTnVOdpO+GEgStEDdsMygWS9znyM5xD/OdAfQ40Q+fkgPRsZw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "97d59b0a-05a9-4a63-9987-5468b21b9aa3",
                            TwoFactorEnabled = false,
                            UserName = "doctor2@hospital.com"
                        },
                        new
                        {
                            Id = "a1212140-332d-4fc5-807d-8fefc129311b",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "dfee0416-d270-4974-8ef3-abf0bfcd1876",
                            Email = "nurse2@hospital.com",
                            EmailConfirmed = false,
                            FirstName = "NurseFirstName2",
                            LastName = "NurseLastName2",
                            LockoutEnabled = false,
                            NormalizedEmail = "NURSE2@HOSPITAL.COM",
                            NormalizedUserName = "NURSE2@HOSPITAL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEDCxOTXL1skuk8209iUTIcIz4oAke/s9cpGJF8mm6dubcWHHb6Jn09mXtlfKjsTjkA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "42e0882b-1140-4dee-8d0e-94dedc65204b",
                            TwoFactorEnabled = false,
                            UserName = "nurse2@hospital.com"
                        },
                        new
                        {
                            Id = "40ae5911-5f60-4ebe-8816-d7b0e9a70385",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "f5e7c957-a668-451e-80c6-f1d19ebb7bf3",
                            Email = "patient2@hospital.com",
                            EmailConfirmed = false,
                            FirstName = "PatientFirstName2",
                            LastName = "PatientLastName2",
                            LockoutEnabled = false,
                            NormalizedEmail = "PATIENT2@HOSPITAL.COM",
                            NormalizedUserName = "PATIENT2@HOSPITAL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEKQQOUE029WkwlfPScWXqQZcpdcJvKJ0MBp1AwulfDoBCMFBnpW9kQraFK1uOn8Beg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "a7dbc6fe-e8e4-4e88-b080-765904564568",
                            TwoFactorEnabled = false,
                            UserName = "patient2@hospital.com"
                        },
                        new
                        {
                            Id = "92a77429-9744-4e29-9d0b-e6d43937f343",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "fa9d87d2-df55-4930-bcbe-57ca775dca1e",
                            Email = "doctor3@hospital.com",
                            EmailConfirmed = false,
                            FirstName = "DoctorFirstName3",
                            LastName = "DoctorLastName3",
                            LockoutEnabled = false,
                            NormalizedEmail = "DOCTOR3@HOSPITAL.COM",
                            NormalizedUserName = "DOCTOR3@HOSPITAL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEIShkjzj2OJIOq+DVH/fhmGOKAScCoP3sN3smAOT+agmaq9XHMJSapKeNOYIXaFIzw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "6691c912-b8e0-4169-aa5c-9e4ff0f1c469",
                            TwoFactorEnabled = false,
                            UserName = "doctor3@hospital.com"
                        },
                        new
                        {
                            Id = "66601ee2-e093-4b49-81d1-b9897d7e9d38",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "cbf0c847-e6e8-4069-9c58-ed5dbb9cc0b4",
                            Email = "nurse3@hospital.com",
                            EmailConfirmed = false,
                            FirstName = "NurseFirstName3",
                            LastName = "NurseLastName3",
                            LockoutEnabled = false,
                            NormalizedEmail = "NURSE3@HOSPITAL.COM",
                            NormalizedUserName = "NURSE3@HOSPITAL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEEsPzjuQkr+qwU6wz2FOPVkzKG+gg8DmcaZubfrhcGDVUpbYGbJK2PHZ9kQoQe5fUw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "ad886431-fa0b-4567-bb84-132d10d4ee35",
                            TwoFactorEnabled = false,
                            UserName = "nurse3@hospital.com"
                        },
                        new
                        {
                            Id = "5086f0bf-ba04-4e17-8f72-d8f7cd02d0b5",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "ca138fb5-43ba-418d-adc8-65f09a01d8bd",
                            Email = "patient3@hospital.com",
                            EmailConfirmed = false,
                            FirstName = "PatientFirstName3",
                            LastName = "PatientLastName3",
                            LockoutEnabled = false,
                            NormalizedEmail = "PATIENT3@HOSPITAL.COM",
                            NormalizedUserName = "PATIENT3@HOSPITAL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEBc6bIqMsMX7fGZ48qTSu9pvFuVd8P3n65tU1MG5cseDjDw3nN29fkpAG9/nbkqnxQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "984c83c0-c818-4735-88aa-4ebd8ef53af4",
                            TwoFactorEnabled = false,
                            UserName = "patient3@hospital.com"
                        },
                        new
                        {
                            Id = "152ea6fa-7cd6-4e1a-8dca-04b45b89d6fc",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "81976ba3-da53-4992-b0b6-3050297e28d5",
                            Email = "doctor4@hospital.com",
                            EmailConfirmed = false,
                            FirstName = "DoctorFirstName4",
                            LastName = "DoctorLastName4",
                            LockoutEnabled = false,
                            NormalizedEmail = "DOCTOR4@HOSPITAL.COM",
                            NormalizedUserName = "DOCTOR4@HOSPITAL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEAgp2O8TBNfcaEeLnbuU9svfV15FMVAhVAZzEZoEA4KsIrIEt9jkYGJbyAPtGW6M1A==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "c0b95ef1-acac-4fab-939a-f983d150dae5",
                            TwoFactorEnabled = false,
                            UserName = "doctor4@hospital.com"
                        },
                        new
                        {
                            Id = "da1d5df6-a9d8-4221-af41-bd0e227b876f",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "7dde9358-9656-4906-b7fa-f407c50db297",
                            Email = "nurse4@hospital.com",
                            EmailConfirmed = false,
                            FirstName = "NurseFirstName4",
                            LastName = "NurseLastName4",
                            LockoutEnabled = false,
                            NormalizedEmail = "NURSE4@HOSPITAL.COM",
                            NormalizedUserName = "NURSE4@HOSPITAL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEGwk8Jr8wvxrTCek4C5fyUvGSnm6G4J/pP+bt+V1XJqWmdUuHHlCnIMe/gnYj3y4mA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "479dec41-57d6-489f-9ac5-14453490105e",
                            TwoFactorEnabled = false,
                            UserName = "nurse4@hospital.com"
                        },
                        new
                        {
                            Id = "67f78a80-d3d1-4c1d-b3ee-28cf910e87ca",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "98146d5c-dc2b-4a0a-a5d1-cea6812b4587",
                            Email = "patient4@hospital.com",
                            EmailConfirmed = false,
                            FirstName = "PatientFirstName4",
                            LastName = "PatientLastName4",
                            LockoutEnabled = false,
                            NormalizedEmail = "PATIENT4@HOSPITAL.COM",
                            NormalizedUserName = "PATIENT4@HOSPITAL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAELo9Edt32oHMVgZtBLgtvNKrasZ9BDv4GQeRUDFzrfWoJSAPnrepc9vNnu2KklgXjg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "54339a33-d346-4fa4-8fe4-5ccbae08f1ad",
                            TwoFactorEnabled = false,
                            UserName = "patient4@hospital.com"
                        },
                        new
                        {
                            Id = "5ac63158-274e-4acc-acf1-b0c2ec142181",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "a06a03db-38de-4326-b94a-09ca7ac74666",
                            Email = "doctor5@hospital.com",
                            EmailConfirmed = false,
                            FirstName = "DoctorFirstName5",
                            LastName = "DoctorLastName5",
                            LockoutEnabled = false,
                            NormalizedEmail = "DOCTOR5@HOSPITAL.COM",
                            NormalizedUserName = "DOCTOR5@HOSPITAL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEO+SSEO4eaggYVGnPq+z00VXE5Vo5kh3RQAv55FegbFlo9RnUJZawbLS0zgq9gpKLA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "387410d4-118c-4477-b761-18807d41a3e2",
                            TwoFactorEnabled = false,
                            UserName = "doctor5@hospital.com"
                        },
                        new
                        {
                            Id = "4407b12e-ec59-49ed-b75f-380f05269380",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "e4e91203-e70b-405e-8b81-fe498987de5f",
                            Email = "nurse5@hospital.com",
                            EmailConfirmed = false,
                            FirstName = "NurseFirstName5",
                            LastName = "NurseLastName5",
                            LockoutEnabled = false,
                            NormalizedEmail = "NURSE5@HOSPITAL.COM",
                            NormalizedUserName = "NURSE5@HOSPITAL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEB8CCbKNImO0zKIbnmdBo+JdJ9p7SpFDH2zp5tiJRCdwVTMbfANa82cguI+lcwYxmQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "865b4be8-ee52-45a2-9211-0d7e45884786",
                            TwoFactorEnabled = false,
                            UserName = "nurse5@hospital.com"
                        },
                        new
                        {
                            Id = "ca875d5f-bddf-41cc-beb8-528f4bc0ac3d",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "e8e346f1-a817-4317-8681-055643b95e08",
                            Email = "patient5@hospital.com",
                            EmailConfirmed = false,
                            FirstName = "PatientFirstName5",
                            LastName = "PatientLastName5",
                            LockoutEnabled = false,
                            NormalizedEmail = "PATIENT5@HOSPITAL.COM",
                            NormalizedUserName = "PATIENT5@HOSPITAL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEGgjtF9CUc1OAiQZ8UKCR6qCx2JR/WLD6O/8a9QSPul/4Qx/crhgGMhyutmOBmmdTg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "b77fb6fd-1a38-4bd8-92a9-a9a356ebd03f",
                            TwoFactorEnabled = false,
                            UserName = "patient5@hospital.com"
                        });
                });

            modelBuilder.Entity("BeHealthy.Domain.Entities.Appointment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AppointmentDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DoctorId")
                        .HasColumnType("integer");

                    b.Property<int>("Duration")
                        .HasColumnType("integer");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int?>("NurseId")
                        .HasColumnType("integer");

                    b.Property<int>("PatientId")
                        .HasColumnType("integer");

                    b.Property<int>("Reason")
                        .HasColumnType("integer");

                    b.Property<int?>("RoomId")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DoctorId");

                    b.HasIndex("NurseId");

                    b.HasIndex("PatientId");

                    b.HasIndex("RoomId");

                    b.ToTable("Appointments", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AppointmentDate = new DateTime(2025, 2, 9, 10, 0, 0, 0, DateTimeKind.Utc),
                            DoctorId = 1,
                            Duration = 60,
                            PatientId = 1,
                            Reason = 0,
                            Status = 1
                        },
                        new
                        {
                            Id = 2,
                            AppointmentDate = new DateTime(2025, 2, 9, 11, 0, 0, 0, DateTimeKind.Utc),
                            DoctorId = 2,
                            Duration = 60,
                            PatientId = 2,
                            Reason = 1,
                            Status = 1
                        },
                        new
                        {
                            Id = 3,
                            AppointmentDate = new DateTime(2025, 2, 9, 12, 0, 0, 0, DateTimeKind.Utc),
                            DoctorId = 3,
                            Duration = 60,
                            PatientId = 3,
                            Reason = 2,
                            Status = 2
                        },
                        new
                        {
                            Id = 4,
                            AppointmentDate = new DateTime(2025, 2, 9, 13, 0, 0, 0, DateTimeKind.Utc),
                            DoctorId = 4,
                            Duration = 60,
                            PatientId = 4,
                            Reason = 3,
                            Status = 0
                        },
                        new
                        {
                            Id = 5,
                            AppointmentDate = new DateTime(2025, 2, 9, 14, 0, 0, 0, DateTimeKind.Utc),
                            DoctorId = 5,
                            Duration = 60,
                            PatientId = 5,
                            Reason = 4,
                            Status = 0
                        },
                        new
                        {
                            Id = 6,
                            AppointmentDate = new DateTime(2025, 2, 10, 10, 0, 0, 0, DateTimeKind.Utc),
                            DoctorId = 1,
                            Duration = 60,
                            PatientId = 2,
                            Reason = 0,
                            Status = 3
                        },
                        new
                        {
                            Id = 7,
                            AppointmentDate = new DateTime(2025, 2, 10, 11, 0, 0, 0, DateTimeKind.Utc),
                            DoctorId = 2,
                            Duration = 60,
                            PatientId = 3,
                            Reason = 1,
                            Status = 0
                        },
                        new
                        {
                            Id = 8,
                            AppointmentDate = new DateTime(2025, 2, 10, 12, 0, 0, 0, DateTimeKind.Utc),
                            DoctorId = 3,
                            Duration = 60,
                            PatientId = 4,
                            Reason = 2,
                            Status = 2
                        },
                        new
                        {
                            Id = 9,
                            AppointmentDate = new DateTime(2025, 2, 10, 13, 0, 0, 0, DateTimeKind.Utc),
                            DoctorId = 4,
                            Duration = 60,
                            PatientId = 5,
                            Reason = 3,
                            Status = 0
                        },
                        new
                        {
                            Id = 10,
                            AppointmentDate = new DateTime(2025, 2, 10, 14, 0, 0, 0, DateTimeKind.Utc),
                            DoctorId = 5,
                            Duration = 60,
                            PatientId = 1,
                            Reason = 4,
                            Status = 3
                        },
                        new
                        {
                            Id = 11,
                            AppointmentDate = new DateTime(2025, 2, 2, 9, 0, 0, 0, DateTimeKind.Utc),
                            DoctorId = 2,
                            Duration = 60,
                            PatientId = 2,
                            Reason = 1,
                            Status = 0
                        },
                        new
                        {
                            Id = 12,
                            AppointmentDate = new DateTime(2025, 2, 13, 12, 0, 0, 0, DateTimeKind.Utc),
                            DoctorId = 3,
                            Duration = 60,
                            PatientId = 3,
                            Reason = 2,
                            Status = 0
                        },
                        new
                        {
                            Id = 13,
                            AppointmentDate = new DateTime(2025, 2, 15, 13, 0, 0, 0, DateTimeKind.Utc),
                            DoctorId = 4,
                            Duration = 60,
                            PatientId = 4,
                            Reason = 3,
                            Status = 0
                        },
                        new
                        {
                            Id = 14,
                            AppointmentDate = new DateTime(2025, 2, 14, 14, 0, 0, 0, DateTimeKind.Utc),
                            DoctorId = 5,
                            Duration = 60,
                            PatientId = 5,
                            Reason = 4,
                            Status = 2
                        },
                        new
                        {
                            Id = 15,
                            AppointmentDate = new DateTime(2025, 2, 13, 10, 0, 0, 0, DateTimeKind.Utc),
                            DoctorId = 1,
                            Duration = 60,
                            PatientId = 2,
                            Reason = 0,
                            Status = 3
                        },
                        new
                        {
                            Id = 16,
                            AppointmentDate = new DateTime(2025, 3, 10, 11, 0, 0, 0, DateTimeKind.Utc),
                            DoctorId = 2,
                            Duration = 60,
                            PatientId = 3,
                            Reason = 1,
                            Status = 0
                        },
                        new
                        {
                            Id = 17,
                            AppointmentDate = new DateTime(2025, 2, 20, 12, 0, 0, 0, DateTimeKind.Utc),
                            DoctorId = 3,
                            Duration = 60,
                            PatientId = 4,
                            Reason = 2,
                            Status = 1
                        },
                        new
                        {
                            Id = 18,
                            AppointmentDate = new DateTime(2025, 3, 3, 13, 0, 0, 0, DateTimeKind.Utc),
                            DoctorId = 4,
                            Duration = 60,
                            PatientId = 5,
                            Reason = 3,
                            Status = 0
                        },
                        new
                        {
                            Id = 19,
                            AppointmentDate = new DateTime(2025, 2, 22, 14, 0, 0, 0, DateTimeKind.Utc),
                            DoctorId = 5,
                            Duration = 60,
                            PatientId = 1,
                            Reason = 4,
                            Status = 3
                        });
                });

            modelBuilder.Entity("BeHealthy.Domain.Entities.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("HeadOfDepartmentId")
                        .HasColumnType("integer");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("HeadOfDepartmentId");

                    b.ToTable("Departments", (string)null);
                });

            modelBuilder.Entity("BeHealthy.Domain.Entities.Doctor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("DepartmentId")
                        .HasColumnType("integer");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Image")
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("SpecialtyId")
                        .HasColumnType("integer");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("SpecialtyId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Doctors", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 2, 9, 5, 35, 18, 44, DateTimeKind.Utc).AddTicks(1499),
                            FirstName = "DoctorFirstName1",
                            LastName = "DoctorLastName1",
                            UserId = "de86fec1-42f2-4088-b643-1f708519ec41"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 2, 9, 5, 35, 18, 272, DateTimeKind.Utc).AddTicks(5582),
                            FirstName = "DoctorFirstName2",
                            LastName = "DoctorLastName2",
                            UserId = "5fb0af0a-86f1-4059-9076-2eb2314e2099"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 2, 9, 5, 35, 18, 482, DateTimeKind.Utc).AddTicks(3152),
                            FirstName = "DoctorFirstName3",
                            LastName = "DoctorLastName3",
                            UserId = "92a77429-9744-4e29-9d0b-e6d43937f343"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2025, 2, 9, 5, 35, 18, 670, DateTimeKind.Utc).AddTicks(4948),
                            FirstName = "DoctorFirstName4",
                            LastName = "DoctorLastName4",
                            UserId = "152ea6fa-7cd6-4e1a-8dca-04b45b89d6fc"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2025, 2, 9, 5, 35, 18, 857, DateTimeKind.Utc).AddTicks(4877),
                            FirstName = "DoctorFirstName5",
                            LastName = "DoctorLastName5",
                            UserId = "5ac63158-274e-4acc-acf1-b0c2ec142181"
                        });
                });

            modelBuilder.Entity("BeHealthy.Domain.Entities.Nurse", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("DepartmentId")
                        .HasColumnType("integer");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Image")
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Nurses", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 2, 9, 5, 35, 18, 126, DateTimeKind.Utc).AddTicks(7733),
                            FirstName = "NurseFirstName1",
                            LastName = "NurseLastName1",
                            UserId = "04692c47-f89c-4fa8-ba2f-987f8519ee66"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 2, 9, 5, 35, 18, 356, DateTimeKind.Utc).AddTicks(2387),
                            FirstName = "NurseFirstName2",
                            LastName = "NurseLastName2",
                            UserId = "a1212140-332d-4fc5-807d-8fefc129311b"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 2, 9, 5, 35, 18, 544, DateTimeKind.Utc).AddTicks(9731),
                            FirstName = "NurseFirstName3",
                            LastName = "NurseLastName3",
                            UserId = "66601ee2-e093-4b49-81d1-b9897d7e9d38"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2025, 2, 9, 5, 35, 18, 732, DateTimeKind.Utc).AddTicks(5692),
                            FirstName = "NurseFirstName4",
                            LastName = "NurseLastName4",
                            UserId = "da1d5df6-a9d8-4221-af41-bd0e227b876f"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2025, 2, 9, 5, 35, 18, 919, DateTimeKind.Utc).AddTicks(9462),
                            FirstName = "NurseFirstName5",
                            LastName = "NurseLastName5",
                            UserId = "4407b12e-ec59-49ed-b75f-380f05269380"
                        });
                });

            modelBuilder.Entity("BeHealthy.Domain.Entities.Patient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("DepartmentId")
                        .HasColumnType("integer");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Image")
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Patients", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 2, 9, 5, 35, 18, 198, DateTimeKind.Utc).AddTicks(5733),
                            FirstName = "PatientFirstName1",
                            LastName = "PatientLastName1",
                            UserId = "686aa49c-ea4d-4c64-a51e-31fd4a94db5b"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 2, 9, 5, 35, 18, 419, DateTimeKind.Utc).AddTicks(5409),
                            FirstName = "PatientFirstName2",
                            LastName = "PatientLastName2",
                            UserId = "40ae5911-5f60-4ebe-8816-d7b0e9a70385"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 2, 9, 5, 35, 18, 607, DateTimeKind.Utc).AddTicks(8558),
                            FirstName = "PatientFirstName3",
                            LastName = "PatientLastName3",
                            UserId = "5086f0bf-ba04-4e17-8f72-d8f7cd02d0b5"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2025, 2, 9, 5, 35, 18, 794, DateTimeKind.Utc).AddTicks(5243),
                            FirstName = "PatientFirstName4",
                            LastName = "PatientLastName4",
                            UserId = "67f78a80-d3d1-4c1d-b3ee-28cf910e87ca"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2025, 2, 9, 5, 35, 18, 982, DateTimeKind.Utc).AddTicks(6045),
                            FirstName = "PatientFirstName5",
                            LastName = "PatientLastName5",
                            UserId = "ca875d5f-bddf-41cc-beb8-528f4bc0ac3d"
                        });
                });

            modelBuilder.Entity("BeHealthy.Domain.Entities.Prescription", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DatePrescribed")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DoctorId")
                        .HasColumnType("integer");

                    b.Property<string>("Dosage")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Medication")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("PatientId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DoctorId");

                    b.HasIndex("PatientId");

                    b.ToTable("Prescriptions", (string)null);
                });

            modelBuilder.Entity("BeHealthy.Domain.Entities.Privilege", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Name")
                        .HasColumnType("integer");

                    b.Property<bool>("Value")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("Privileges");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = 0,
                            Value = false
                        },
                        new
                        {
                            Id = 2,
                            Name = 1,
                            Value = false
                        });
                });

            modelBuilder.Entity("BeHealthy.Domain.Entities.RolePrivilege", b =>
                {
                    b.Property<short>("Role")
                        .HasColumnType("smallint");

                    b.Property<int>("PrivilegeId")
                        .HasColumnType("integer");

                    b.HasKey("Role", "PrivilegeId");

                    b.HasIndex("PrivilegeId");

                    b.ToTable("RolePrivileges");

                    b.HasData(
                        new
                        {
                            Role = (short)2,
                            PrivilegeId = 1
                        },
                        new
                        {
                            Role = (short)2,
                            PrivilegeId = 2
                        },
                        new
                        {
                            Role = (short)4,
                            PrivilegeId = 1
                        },
                        new
                        {
                            Role = (short)4,
                            PrivilegeId = 2
                        },
                        new
                        {
                            Role = (short)3,
                            PrivilegeId = 1
                        },
                        new
                        {
                            Role = (short)3,
                            PrivilegeId = 2
                        });
                });

            modelBuilder.Entity("BeHealthy.Domain.Entities.Room", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Number")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.ToTable("Rooms", (string)null);
                });

            modelBuilder.Entity("BeHealthy.Domain.Entities.Specialty", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Specialities", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "0",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = "1",
                            Name = "Staff",
                            NormalizedName = "STAFF"
                        },
                        new
                        {
                            Id = "2",
                            Name = "Doctor",
                            NormalizedName = "DOCTOR"
                        },
                        new
                        {
                            Id = "3",
                            Name = "Nurse",
                            NormalizedName = "NURSE"
                        },
                        new
                        {
                            Id = "4",
                            Name = "Patient",
                            NormalizedName = "PATIENT"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "admin",
                            RoleId = "0"
                        },
                        new
                        {
                            UserId = "de86fec1-42f2-4088-b643-1f708519ec41",
                            RoleId = "2"
                        },
                        new
                        {
                            UserId = "04692c47-f89c-4fa8-ba2f-987f8519ee66",
                            RoleId = "3"
                        },
                        new
                        {
                            UserId = "686aa49c-ea4d-4c64-a51e-31fd4a94db5b",
                            RoleId = "3"
                        },
                        new
                        {
                            UserId = "5fb0af0a-86f1-4059-9076-2eb2314e2099",
                            RoleId = "2"
                        },
                        new
                        {
                            UserId = "a1212140-332d-4fc5-807d-8fefc129311b",
                            RoleId = "3"
                        },
                        new
                        {
                            UserId = "40ae5911-5f60-4ebe-8816-d7b0e9a70385",
                            RoleId = "3"
                        },
                        new
                        {
                            UserId = "92a77429-9744-4e29-9d0b-e6d43937f343",
                            RoleId = "2"
                        },
                        new
                        {
                            UserId = "66601ee2-e093-4b49-81d1-b9897d7e9d38",
                            RoleId = "3"
                        },
                        new
                        {
                            UserId = "5086f0bf-ba04-4e17-8f72-d8f7cd02d0b5",
                            RoleId = "3"
                        },
                        new
                        {
                            UserId = "152ea6fa-7cd6-4e1a-8dca-04b45b89d6fc",
                            RoleId = "2"
                        },
                        new
                        {
                            UserId = "da1d5df6-a9d8-4221-af41-bd0e227b876f",
                            RoleId = "3"
                        },
                        new
                        {
                            UserId = "67f78a80-d3d1-4c1d-b3ee-28cf910e87ca",
                            RoleId = "3"
                        },
                        new
                        {
                            UserId = "5ac63158-274e-4acc-acf1-b0c2ec142181",
                            RoleId = "2"
                        },
                        new
                        {
                            UserId = "4407b12e-ec59-49ed-b75f-380f05269380",
                            RoleId = "3"
                        },
                        new
                        {
                            UserId = "ca875d5f-bddf-41cc-beb8-528f4bc0ac3d",
                            RoleId = "3"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("BeHealthy.Domain.Entities.Appointment", b =>
                {
                    b.HasOne("BeHealthy.Domain.Entities.Doctor", "Doctor")
                        .WithMany("Appointments")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BeHealthy.Domain.Entities.Nurse", "Nurse")
                        .WithMany("Appointments")
                        .HasForeignKey("NurseId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("BeHealthy.Domain.Entities.Patient", "Patient")
                        .WithMany("Appointments")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BeHealthy.Domain.Entities.Room", "Room")
                        .WithMany("Appointments")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Doctor");

                    b.Navigation("Nurse");

                    b.Navigation("Patient");

                    b.Navigation("Room");
                });

            modelBuilder.Entity("BeHealthy.Domain.Entities.Department", b =>
                {
                    b.HasOne("BeHealthy.Domain.Entities.Doctor", "HeadOfDepartment")
                        .WithMany()
                        .HasForeignKey("HeadOfDepartmentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("HeadOfDepartment");
                });

            modelBuilder.Entity("BeHealthy.Domain.Entities.Doctor", b =>
                {
                    b.HasOne("BeHealthy.Domain.Entities.Department", "Department")
                        .WithMany("Doctors")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("BeHealthy.Domain.Entities.Specialty", "Specialty")
                        .WithMany("Doctors")
                        .HasForeignKey("SpecialtyId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("BeHealthy.Domain.Entities.ApplicationUser", "User")
                        .WithOne("Doctor")
                        .HasForeignKey("BeHealthy.Domain.Entities.Doctor", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");

                    b.Navigation("Specialty");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BeHealthy.Domain.Entities.Nurse", b =>
                {
                    b.HasOne("BeHealthy.Domain.Entities.Department", "Department")
                        .WithMany("Nurses")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("BeHealthy.Domain.Entities.ApplicationUser", "User")
                        .WithOne("Nurse")
                        .HasForeignKey("BeHealthy.Domain.Entities.Nurse", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BeHealthy.Domain.Entities.Patient", b =>
                {
                    b.HasOne("BeHealthy.Domain.Entities.Department", "Department")
                        .WithMany("Patients")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("BeHealthy.Domain.Entities.ApplicationUser", "User")
                        .WithOne("Patient")
                        .HasForeignKey("BeHealthy.Domain.Entities.Patient", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BeHealthy.Domain.Entities.Prescription", b =>
                {
                    b.HasOne("BeHealthy.Domain.Entities.Doctor", "Doctor")
                        .WithMany()
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BeHealthy.Domain.Entities.Patient", "Patient")
                        .WithMany()
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Doctor");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("BeHealthy.Domain.Entities.RolePrivilege", b =>
                {
                    b.HasOne("BeHealthy.Domain.Entities.Privilege", "Privilege")
                        .WithMany("RolePrivileges")
                        .HasForeignKey("PrivilegeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Privilege");
                });

            modelBuilder.Entity("BeHealthy.Domain.Entities.Room", b =>
                {
                    b.HasOne("BeHealthy.Domain.Entities.Department", "Department")
                        .WithMany("Rooms")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("BeHealthy.Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("BeHealthy.Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BeHealthy.Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("BeHealthy.Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BeHealthy.Domain.Entities.ApplicationUser", b =>
                {
                    b.Navigation("Doctor");

                    b.Navigation("Nurse");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("BeHealthy.Domain.Entities.Department", b =>
                {
                    b.Navigation("Doctors");

                    b.Navigation("Nurses");

                    b.Navigation("Patients");

                    b.Navigation("Rooms");
                });

            modelBuilder.Entity("BeHealthy.Domain.Entities.Doctor", b =>
                {
                    b.Navigation("Appointments");
                });

            modelBuilder.Entity("BeHealthy.Domain.Entities.Nurse", b =>
                {
                    b.Navigation("Appointments");
                });

            modelBuilder.Entity("BeHealthy.Domain.Entities.Patient", b =>
                {
                    b.Navigation("Appointments");
                });

            modelBuilder.Entity("BeHealthy.Domain.Entities.Privilege", b =>
                {
                    b.Navigation("RolePrivileges");
                });

            modelBuilder.Entity("BeHealthy.Domain.Entities.Room", b =>
                {
                    b.Navigation("Appointments");
                });

            modelBuilder.Entity("BeHealthy.Domain.Entities.Specialty", b =>
                {
                    b.Navigation("Doctors");
                });
#pragma warning restore 612, 618
        }
    }
}
