// <auto-generated />
using System;
using BeHealthy.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BeHealthy.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BeHealthy.Domain.Entities.AppSetting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Caption")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Group")
                        .HasColumnType("integer");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("AppSettings", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Caption = "Requires Room for Appointment",
                            Description = "Indicates if a room is required for an appointment.",
                            Group = 0,
                            Key = "AppointmentRequiresRoom",
                            Type = 0,
                            Value = "false"
                        },
                        new
                        {
                            Id = 2,
                            Caption = "Do not allow doctors without a specialty",
                            Description = "Indicates if doctors without a specialty should be allowed.",
                            Group = 2,
                            Key = "DoNotAllowDoctorWithoutSpecialty",
                            Type = 0,
                            Value = "false"
                        },
                        new
                        {
                            Id = 3,
                            Caption = "Department requires supervisor",
                            Description = "Indicates if a department requires a supervisor.",
                            Group = 1,
                            Key = "DepartmentRequiresSupervisor",
                            Type = 0,
                            Value = "false"
                        },
                        new
                        {
                            Id = 4,
                            Caption = "Default Department Supervision",
                            Description = "The default supervisor selection for departments.",
                            Group = 1,
                            Key = "DefaultDepartmentSupervison",
                            Type = 1,
                            Value = "0"
                        });
                });

            modelBuilder.Entity("BeHealthy.Domain.Entities.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("Address")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Gender")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("ApplicationUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "admin",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "f987241d-ff6d-4122-9763-4bfd8da0369b",
                            Email = "admin@gmail.com",
                            EmailConfirmed = false,
                            FirstName = "Admin",
                            LastName = "User",
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN@GMAIL.COM",
                            NormalizedUserName = "ADMIN@GMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEKka1TKn/MvonpDnA9MLvZ5bDVp2Rxqg6dtkgUaS6fC4UZNKjhsd84G3LjDKlBHitQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "f5a118cf-2c54-414e-b590-81047d8f9924",
                            TwoFactorEnabled = false,
                            UserName = "admin@gmail.com"
                        },
                        new
                        {
                            Id = "dc440c59-36be-425d-b310-07ccc49bac92",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "f65420d4-75fc-4ae5-8470-4b240dea5729",
                            Email = "doctor1@hospital.com",
                            EmailConfirmed = false,
                            FirstName = "DoctorFirstName1",
                            LastName = "DoctorLastName1",
                            LockoutEnabled = false,
                            NormalizedEmail = "DOCTOR1@HOSPITAL.COM",
                            NormalizedUserName = "DOCTOR1@HOSPITAL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEDXYbl3U6II7nTvY+zDKEFV41I+69SYGmGOMFxm4Nslpfic833w23vxMwlYuQgqbTQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "78614305-0c5d-48b3-97be-e7025cae86fe",
                            TwoFactorEnabled = false,
                            UserName = "doctor1@hospital.com"
                        },
                        new
                        {
                            Id = "b6ace12e-e615-4c01-8bf6-8a653c1c275f",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "234bed90-4bfa-468e-943b-9ed8d27cba59",
                            Email = "nurse1@hospital.com",
                            EmailConfirmed = false,
                            FirstName = "NurseFirstName1",
                            LastName = "NurseLastName1",
                            LockoutEnabled = false,
                            NormalizedEmail = "NURSE1@HOSPITAL.COM",
                            NormalizedUserName = "NURSE1@HOSPITAL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEOlPuzQXzECSCKsZDoZYHdoGkcvfPD8iyQR9qhGt9hEkVnaXRAJbihbU8hN/YDHrAg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "575323df-7ab9-4070-9ffd-979c268adb03",
                            TwoFactorEnabled = false,
                            UserName = "nurse1@hospital.com"
                        },
                        new
                        {
                            Id = "62330df5-5a81-4384-822d-18277113df6e",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "913e2480-2703-420f-b301-ccff9f928e77",
                            Email = "patient1@hospital.com",
                            EmailConfirmed = false,
                            FirstName = "PatientFirstName1",
                            LastName = "PatientLastName1",
                            LockoutEnabled = false,
                            NormalizedEmail = "PATIENT1@HOSPITAL.COM",
                            NormalizedUserName = "PATIENT1@HOSPITAL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEFUz9qfcSXRUbpDhF/UKob+DB1L4wymdCivZePAh72nAwCvYnr0J64jr9e0jw/vjIw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "5e6efb6a-7ce8-41b1-8bed-e94b04362dd5",
                            TwoFactorEnabled = false,
                            UserName = "patient1@hospital.com"
                        },
                        new
                        {
                            Id = "4cbd075f-5b48-48eb-8d18-3af50b6c27a3",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "df581899-b3ae-4df5-9620-ade6021e9a33",
                            Email = "doctor2@hospital.com",
                            EmailConfirmed = false,
                            FirstName = "DoctorFirstName2",
                            LastName = "DoctorLastName2",
                            LockoutEnabled = false,
                            NormalizedEmail = "DOCTOR2@HOSPITAL.COM",
                            NormalizedUserName = "DOCTOR2@HOSPITAL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAELBnml5Kxo9E2AahIhDgIri24i9uUB3O8t2Xoj37mGfwK6xMq+k/6XnkHdFVRqKQiA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "056a719f-e2cc-46e7-965f-018e8045ff4b",
                            TwoFactorEnabled = false,
                            UserName = "doctor2@hospital.com"
                        },
                        new
                        {
                            Id = "44d09ecb-330a-47a4-91f4-4e6d81290572",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "0aabde88-e2b9-48cb-9f05-fedf4f83cd5c",
                            Email = "nurse2@hospital.com",
                            EmailConfirmed = false,
                            FirstName = "NurseFirstName2",
                            LastName = "NurseLastName2",
                            LockoutEnabled = false,
                            NormalizedEmail = "NURSE2@HOSPITAL.COM",
                            NormalizedUserName = "NURSE2@HOSPITAL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEOf7QTfXPAfqpxGq0ZM5Vuk5LjsKhWxfZrWKJ/xBAV7L9TyKTj9k+aMEgOZPRUsz1Q==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "b9fa698b-963a-43fb-9a60-3d5f1834fd93",
                            TwoFactorEnabled = false,
                            UserName = "nurse2@hospital.com"
                        },
                        new
                        {
                            Id = "0021c43b-b158-4070-863c-c59c2d735a54",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "cb801718-8b8c-4c7e-b0ad-41f4776c3492",
                            Email = "patient2@hospital.com",
                            EmailConfirmed = false,
                            FirstName = "PatientFirstName2",
                            LastName = "PatientLastName2",
                            LockoutEnabled = false,
                            NormalizedEmail = "PATIENT2@HOSPITAL.COM",
                            NormalizedUserName = "PATIENT2@HOSPITAL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEBDn9wKd+vt8OT4cv/tu6A8NBYkLV2lSGn4N8l0zi40tHHd9M3kQmcPpwJ12Hkn7iQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "45853418-03f3-47de-a663-254e15c6e9db",
                            TwoFactorEnabled = false,
                            UserName = "patient2@hospital.com"
                        },
                        new
                        {
                            Id = "af846fa7-cbe0-4a92-9198-b9ab763b1ad6",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "ca08072a-c15d-44d6-b2e6-d03d535c9252",
                            Email = "doctor3@hospital.com",
                            EmailConfirmed = false,
                            FirstName = "DoctorFirstName3",
                            LastName = "DoctorLastName3",
                            LockoutEnabled = false,
                            NormalizedEmail = "DOCTOR3@HOSPITAL.COM",
                            NormalizedUserName = "DOCTOR3@HOSPITAL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEEXR9ACndZN30nARmS0uE1twu7dLGfXysm7/scLvX6rNdlq5wqWjOn6eFC/jKdd5uw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "264c47d7-00f7-4c20-835f-5e62703bdea6",
                            TwoFactorEnabled = false,
                            UserName = "doctor3@hospital.com"
                        },
                        new
                        {
                            Id = "8667a65a-b2f0-442f-8e3c-0c3b6230ae7a",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "0c6dc6c5-bc65-423f-afc9-29a57e215ecf",
                            Email = "nurse3@hospital.com",
                            EmailConfirmed = false,
                            FirstName = "NurseFirstName3",
                            LastName = "NurseLastName3",
                            LockoutEnabled = false,
                            NormalizedEmail = "NURSE3@HOSPITAL.COM",
                            NormalizedUserName = "NURSE3@HOSPITAL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEKiOA47vlf9MKraNy+AjryVOoex9/JMVe693nNCi58Bga6ssXRXVRdbvQhWDtcN5sw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "2dc46482-a011-4691-8199-971843af3e69",
                            TwoFactorEnabled = false,
                            UserName = "nurse3@hospital.com"
                        },
                        new
                        {
                            Id = "56d017a4-a4ad-466f-bbec-05f52fd10437",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "0dfa5155-1f36-430b-981b-efb53a1a0fd7",
                            Email = "patient3@hospital.com",
                            EmailConfirmed = false,
                            FirstName = "PatientFirstName3",
                            LastName = "PatientLastName3",
                            LockoutEnabled = false,
                            NormalizedEmail = "PATIENT3@HOSPITAL.COM",
                            NormalizedUserName = "PATIENT3@HOSPITAL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEINsQW7vuOZn//6OHVwI4qeBjH52gYT5Wc7/7jqcytOwYRI4IWn7uVKdvFeB9nb3+Q==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "aef90371-a798-48cb-a7a3-ac160dd93edf",
                            TwoFactorEnabled = false,
                            UserName = "patient3@hospital.com"
                        },
                        new
                        {
                            Id = "290a8252-f74f-4432-9b44-a10c9bcdccbd",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "2bb32c8e-0077-4970-9ced-1ea95293faf1",
                            Email = "doctor4@hospital.com",
                            EmailConfirmed = false,
                            FirstName = "DoctorFirstName4",
                            LastName = "DoctorLastName4",
                            LockoutEnabled = false,
                            NormalizedEmail = "DOCTOR4@HOSPITAL.COM",
                            NormalizedUserName = "DOCTOR4@HOSPITAL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAECMEHapwSd+qvUUyeO0zPrgMZC227DIq+H+Uh7457qCS0Q1/sLjFml4OOco1IBTwsQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "74bf01c1-a6e3-4b4e-b94c-75bcb1cacce3",
                            TwoFactorEnabled = false,
                            UserName = "doctor4@hospital.com"
                        },
                        new
                        {
                            Id = "7bcd232d-4185-4dc6-a057-cae3ee0c6658",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "2b11e8b0-5381-42b9-8092-e4a667035672",
                            Email = "nurse4@hospital.com",
                            EmailConfirmed = false,
                            FirstName = "NurseFirstName4",
                            LastName = "NurseLastName4",
                            LockoutEnabled = false,
                            NormalizedEmail = "NURSE4@HOSPITAL.COM",
                            NormalizedUserName = "NURSE4@HOSPITAL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEA1NWfMv1KvheaOhXRpHjRLEdmjoCFCY9BlceFGfHG5VGorwCE+rbDAM+X92niMnjA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "656f843b-457e-4c78-86cf-4b4c2384ee22",
                            TwoFactorEnabled = false,
                            UserName = "nurse4@hospital.com"
                        },
                        new
                        {
                            Id = "46c27294-8635-46e6-8c66-81a569d18dca",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "a7091eda-7d8e-45e0-a329-c164b116cb90",
                            Email = "patient4@hospital.com",
                            EmailConfirmed = false,
                            FirstName = "PatientFirstName4",
                            LastName = "PatientLastName4",
                            LockoutEnabled = false,
                            NormalizedEmail = "PATIENT4@HOSPITAL.COM",
                            NormalizedUserName = "PATIENT4@HOSPITAL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEDnV45IrDS3+AOcIEJDcBlzDGZyU83fOzhH05K58OqVJQf9RZSR6H9maoY9spNnSzA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "e9eb44b5-e8e4-4872-ac8c-139bcea0bbe1",
                            TwoFactorEnabled = false,
                            UserName = "patient4@hospital.com"
                        },
                        new
                        {
                            Id = "d2ae1474-9b71-457e-af0c-897b11ec41fe",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "7efef068-d26c-4c9b-b601-00518e2d696e",
                            Email = "doctor5@hospital.com",
                            EmailConfirmed = false,
                            FirstName = "DoctorFirstName5",
                            LastName = "DoctorLastName5",
                            LockoutEnabled = false,
                            NormalizedEmail = "DOCTOR5@HOSPITAL.COM",
                            NormalizedUserName = "DOCTOR5@HOSPITAL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAECHdzD5rbkChZCo0JF22W81loFBQj1z1u75oT44yJSYoo99w6tkdb4bK0uBtJq1pkw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "aab3c503-b3da-46f4-80d2-d98e157bfb71",
                            TwoFactorEnabled = false,
                            UserName = "doctor5@hospital.com"
                        },
                        new
                        {
                            Id = "2c928c85-219d-4b81-8d83-0114828491d5",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "13e402ee-ff9c-4435-8823-c8bd7bbb25c9",
                            Email = "nurse5@hospital.com",
                            EmailConfirmed = false,
                            FirstName = "NurseFirstName5",
                            LastName = "NurseLastName5",
                            LockoutEnabled = false,
                            NormalizedEmail = "NURSE5@HOSPITAL.COM",
                            NormalizedUserName = "NURSE5@HOSPITAL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEBGJBKW3PBh9T4grhY4KxSEIa7aDVZ/qYdkcRVstyFMBdnKiF3GzrR85glebfi+yvA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "2d29662b-25e0-43f7-8705-658989cf8a81",
                            TwoFactorEnabled = false,
                            UserName = "nurse5@hospital.com"
                        },
                        new
                        {
                            Id = "dca4b91e-27f6-41da-b51b-1e4197664faa",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "6e3e981d-afcb-4749-804b-de4d15fdff49",
                            Email = "patient5@hospital.com",
                            EmailConfirmed = false,
                            FirstName = "PatientFirstName5",
                            LastName = "PatientLastName5",
                            LockoutEnabled = false,
                            NormalizedEmail = "PATIENT5@HOSPITAL.COM",
                            NormalizedUserName = "PATIENT5@HOSPITAL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEHVdptd34GtmLQzKVNgomNzZIsWXKavzZmiBf3+0wwdyDGWIk1U9NPzYIgKaP+l7wQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "43f2e9d3-2cb7-4316-9d5c-232539fb2e17",
                            TwoFactorEnabled = false,
                            UserName = "patient5@hospital.com"
                        });
                });

            modelBuilder.Entity("BeHealthy.Domain.Entities.Appointment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AppointmentDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DoctorId")
                        .HasColumnType("integer");

                    b.Property<int>("Duration")
                        .HasColumnType("integer");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int?>("NurseId")
                        .HasColumnType("integer");

                    b.Property<int>("PatientId")
                        .HasColumnType("integer");

                    b.Property<int>("Reason")
                        .HasColumnType("integer");

                    b.Property<int?>("RoomId")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DoctorId");

                    b.HasIndex("NurseId");

                    b.HasIndex("PatientId");

                    b.HasIndex("RoomId");

                    b.ToTable("Appointments", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AppointmentDate = new DateTime(2025, 2, 6, 10, 0, 0, 0, DateTimeKind.Utc),
                            DoctorId = 1,
                            Duration = 60,
                            PatientId = 1,
                            Reason = 0,
                            Status = 1
                        },
                        new
                        {
                            Id = 2,
                            AppointmentDate = new DateTime(2025, 2, 8, 11, 0, 0, 0, DateTimeKind.Utc),
                            DoctorId = 2,
                            Duration = 60,
                            PatientId = 2,
                            Reason = 1,
                            Status = 2
                        },
                        new
                        {
                            Id = 3,
                            AppointmentDate = new DateTime(2025, 2, 9, 9, 0, 0, 0, DateTimeKind.Utc),
                            DoctorId = 3,
                            Duration = 60,
                            PatientId = 3,
                            Reason = 1,
                            Status = 2
                        },
                        new
                        {
                            Id = 4,
                            AppointmentDate = new DateTime(2025, 2, 10, 12, 0, 0, 0, DateTimeKind.Utc),
                            DoctorId = 4,
                            Duration = 60,
                            PatientId = 4,
                            Reason = 1,
                            Status = 1
                        },
                        new
                        {
                            Id = 5,
                            AppointmentDate = new DateTime(2025, 2, 11, 12, 0, 0, 0, DateTimeKind.Utc),
                            DoctorId = 3,
                            Duration = 60,
                            PatientId = 3,
                            Reason = 2,
                            Status = 0
                        },
                        new
                        {
                            Id = 6,
                            AppointmentDate = new DateTime(2025, 2, 11, 14, 0, 0, 0, DateTimeKind.Utc),
                            DoctorId = 4,
                            Duration = 60,
                            PatientId = 4,
                            Reason = 3,
                            Status = 3
                        },
                        new
                        {
                            Id = 7,
                            AppointmentDate = new DateTime(2025, 2, 11, 9, 0, 0, 0, DateTimeKind.Utc),
                            DoctorId = 4,
                            Duration = 60,
                            PatientId = 1,
                            Reason = 3,
                            Status = 0
                        },
                        new
                        {
                            Id = 8,
                            AppointmentDate = new DateTime(2025, 2, 11, 11, 0, 0, 0, DateTimeKind.Utc),
                            DoctorId = 3,
                            Duration = 60,
                            PatientId = 2,
                            Reason = 3,
                            Status = 0
                        },
                        new
                        {
                            Id = 9,
                            AppointmentDate = new DateTime(2025, 2, 11, 15, 0, 0, 0, DateTimeKind.Utc),
                            DoctorId = 1,
                            Duration = 60,
                            PatientId = 1,
                            Reason = 3,
                            Status = 3
                        },
                        new
                        {
                            Id = 10,
                            AppointmentDate = new DateTime(2025, 2, 12, 10, 0, 0, 0, DateTimeKind.Utc),
                            DoctorId = 5,
                            Duration = 60,
                            PatientId = 5,
                            Reason = 4,
                            Status = 0
                        },
                        new
                        {
                            Id = 11,
                            AppointmentDate = new DateTime(2025, 2, 13, 11, 0, 0, 0, DateTimeKind.Utc),
                            DoctorId = 1,
                            Duration = 60,
                            PatientId = 2,
                            Reason = 0,
                            Status = 3
                        },
                        new
                        {
                            Id = 12,
                            AppointmentDate = new DateTime(2025, 2, 14, 12, 0, 0, 0, DateTimeKind.Utc),
                            DoctorId = 2,
                            Duration = 60,
                            PatientId = 3,
                            Reason = 1,
                            Status = 0
                        },
                        new
                        {
                            Id = 13,
                            AppointmentDate = new DateTime(2025, 2, 21, 13, 0, 0, 0, DateTimeKind.Utc),
                            DoctorId = 4,
                            Duration = 60,
                            PatientId = 5,
                            Reason = 3,
                            Status = 0
                        },
                        new
                        {
                            Id = 14,
                            AppointmentDate = new DateTime(2025, 2, 26, 14, 0, 0, 0, DateTimeKind.Utc),
                            DoctorId = 5,
                            Duration = 60,
                            PatientId = 1,
                            Reason = 4,
                            Status = 3
                        });
                });

            modelBuilder.Entity("BeHealthy.Domain.Entities.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("HeadOfDepartmentId")
                        .HasColumnType("integer");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("HeadOfDepartmentId");

                    b.ToTable("Departments", (string)null);
                });

            modelBuilder.Entity("BeHealthy.Domain.Entities.Doctor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("DepartmentId")
                        .HasColumnType("integer");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Image")
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("SpecialtyId")
                        .HasColumnType("integer");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("SpecialtyId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Doctors", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 2, 11, 18, 53, 39, 332, DateTimeKind.Utc).AddTicks(9653),
                            FirstName = "DoctorFirstName1",
                            LastName = "DoctorLastName1",
                            UserId = "dc440c59-36be-425d-b310-07ccc49bac92"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 2, 11, 18, 53, 39, 524, DateTimeKind.Utc).AddTicks(974),
                            FirstName = "DoctorFirstName2",
                            LastName = "DoctorLastName2",
                            UserId = "4cbd075f-5b48-48eb-8d18-3af50b6c27a3"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 2, 11, 18, 53, 39, 727, DateTimeKind.Utc).AddTicks(6107),
                            FirstName = "DoctorFirstName3",
                            LastName = "DoctorLastName3",
                            UserId = "af846fa7-cbe0-4a92-9198-b9ab763b1ad6"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2025, 2, 11, 18, 53, 39, 918, DateTimeKind.Utc).AddTicks(5228),
                            FirstName = "DoctorFirstName4",
                            LastName = "DoctorLastName4",
                            UserId = "290a8252-f74f-4432-9b44-a10c9bcdccbd"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2025, 2, 11, 18, 53, 40, 108, DateTimeKind.Utc).AddTicks(6450),
                            FirstName = "DoctorFirstName5",
                            LastName = "DoctorLastName5",
                            UserId = "d2ae1474-9b71-457e-af0c-897b11ec41fe"
                        });
                });

            modelBuilder.Entity("BeHealthy.Domain.Entities.Nurse", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("DepartmentId")
                        .HasColumnType("integer");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Image")
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Nurses", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 2, 11, 18, 53, 39, 396, DateTimeKind.Utc).AddTicks(5867),
                            FirstName = "NurseFirstName1",
                            LastName = "NurseLastName1",
                            UserId = "b6ace12e-e615-4c01-8bf6-8a653c1c275f"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 2, 11, 18, 53, 39, 597, DateTimeKind.Utc).AddTicks(774),
                            FirstName = "NurseFirstName2",
                            LastName = "NurseLastName2",
                            UserId = "44d09ecb-330a-47a4-91f4-4e6d81290572"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 2, 11, 18, 53, 39, 791, DateTimeKind.Utc).AddTicks(4857),
                            FirstName = "NurseFirstName3",
                            LastName = "NurseLastName3",
                            UserId = "8667a65a-b2f0-442f-8e3c-0c3b6230ae7a"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2025, 2, 11, 18, 53, 39, 981, DateTimeKind.Utc).AddTicks(9176),
                            FirstName = "NurseFirstName4",
                            LastName = "NurseLastName4",
                            UserId = "7bcd232d-4185-4dc6-a057-cae3ee0c6658"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2025, 2, 11, 18, 53, 40, 172, DateTimeKind.Utc).AddTicks(507),
                            FirstName = "NurseFirstName5",
                            LastName = "NurseLastName5",
                            UserId = "2c928c85-219d-4b81-8d83-0114828491d5"
                        });
                });

            modelBuilder.Entity("BeHealthy.Domain.Entities.Patient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("DepartmentId")
                        .HasColumnType("integer");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Image")
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Patients", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 2, 11, 18, 53, 39, 460, DateTimeKind.Utc).AddTicks(4192),
                            FirstName = "PatientFirstName1",
                            LastName = "PatientLastName1",
                            UserId = "62330df5-5a81-4384-822d-18277113df6e"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 2, 11, 18, 53, 39, 663, DateTimeKind.Utc).AddTicks(5447),
                            FirstName = "PatientFirstName2",
                            LastName = "PatientLastName2",
                            UserId = "0021c43b-b158-4070-863c-c59c2d735a54"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 2, 11, 18, 53, 39, 855, DateTimeKind.Utc).AddTicks(559),
                            FirstName = "PatientFirstName3",
                            LastName = "PatientLastName3",
                            UserId = "56d017a4-a4ad-466f-bbec-05f52fd10437"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2025, 2, 11, 18, 53, 40, 45, DateTimeKind.Utc).AddTicks(5678),
                            FirstName = "PatientFirstName4",
                            LastName = "PatientLastName4",
                            UserId = "46c27294-8635-46e6-8c66-81a569d18dca"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2025, 2, 11, 18, 53, 40, 235, DateTimeKind.Utc).AddTicks(451),
                            FirstName = "PatientFirstName5",
                            LastName = "PatientLastName5",
                            UserId = "dca4b91e-27f6-41da-b51b-1e4197664faa"
                        });
                });

            modelBuilder.Entity("BeHealthy.Domain.Entities.Prescription", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DatePrescribed")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DoctorId")
                        .HasColumnType("integer");

                    b.Property<string>("Dosage")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Medication")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("PatientId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DoctorId");

                    b.HasIndex("PatientId");

                    b.ToTable("Prescriptions", (string)null);
                });

            modelBuilder.Entity("BeHealthy.Domain.Entities.Privilege", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Name")
                        .HasColumnType("integer");

                    b.Property<short>("Role")
                        .HasColumnType("smallint");

                    b.Property<bool>("Value")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("Privileges");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = 0,
                            Role = (short)2,
                            Value = true
                        },
                        new
                        {
                            Id = 2,
                            Name = 1,
                            Role = (short)2,
                            Value = true
                        },
                        new
                        {
                            Id = 3,
                            Name = 4,
                            Role = (short)2,
                            Value = true
                        },
                        new
                        {
                            Id = 4,
                            Name = 5,
                            Role = (short)2,
                            Value = false
                        },
                        new
                        {
                            Id = 5,
                            Name = 3,
                            Role = (short)2,
                            Value = false
                        },
                        new
                        {
                            Id = 6,
                            Name = 2,
                            Role = (short)2,
                            Value = false
                        },
                        new
                        {
                            Id = 7,
                            Name = 6,
                            Role = (short)4,
                            Value = false
                        },
                        new
                        {
                            Id = 8,
                            Name = 7,
                            Role = (short)4,
                            Value = false
                        },
                        new
                        {
                            Id = 9,
                            Name = 8,
                            Role = (short)3,
                            Value = false
                        },
                        new
                        {
                            Id = 10,
                            Name = 9,
                            Role = (short)3,
                            Value = false
                        },
                        new
                        {
                            Id = 11,
                            Name = 10,
                            Role = (short)3,
                            Value = false
                        });
                });

            modelBuilder.Entity("BeHealthy.Domain.Entities.Room", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Number")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.ToTable("Rooms", (string)null);
                });

            modelBuilder.Entity("BeHealthy.Domain.Entities.Specialty", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Specialities", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "0",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = "1",
                            Name = "Staff",
                            NormalizedName = "STAFF"
                        },
                        new
                        {
                            Id = "2",
                            Name = "Doctor",
                            NormalizedName = "DOCTOR"
                        },
                        new
                        {
                            Id = "3",
                            Name = "Nurse",
                            NormalizedName = "NURSE"
                        },
                        new
                        {
                            Id = "4",
                            Name = "Patient",
                            NormalizedName = "PATIENT"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "admin",
                            RoleId = "0"
                        },
                        new
                        {
                            UserId = "dc440c59-36be-425d-b310-07ccc49bac92",
                            RoleId = "2"
                        },
                        new
                        {
                            UserId = "b6ace12e-e615-4c01-8bf6-8a653c1c275f",
                            RoleId = "3"
                        },
                        new
                        {
                            UserId = "62330df5-5a81-4384-822d-18277113df6e",
                            RoleId = "4"
                        },
                        new
                        {
                            UserId = "4cbd075f-5b48-48eb-8d18-3af50b6c27a3",
                            RoleId = "2"
                        },
                        new
                        {
                            UserId = "44d09ecb-330a-47a4-91f4-4e6d81290572",
                            RoleId = "3"
                        },
                        new
                        {
                            UserId = "0021c43b-b158-4070-863c-c59c2d735a54",
                            RoleId = "4"
                        },
                        new
                        {
                            UserId = "af846fa7-cbe0-4a92-9198-b9ab763b1ad6",
                            RoleId = "2"
                        },
                        new
                        {
                            UserId = "8667a65a-b2f0-442f-8e3c-0c3b6230ae7a",
                            RoleId = "3"
                        },
                        new
                        {
                            UserId = "56d017a4-a4ad-466f-bbec-05f52fd10437",
                            RoleId = "4"
                        },
                        new
                        {
                            UserId = "290a8252-f74f-4432-9b44-a10c9bcdccbd",
                            RoleId = "2"
                        },
                        new
                        {
                            UserId = "7bcd232d-4185-4dc6-a057-cae3ee0c6658",
                            RoleId = "3"
                        },
                        new
                        {
                            UserId = "46c27294-8635-46e6-8c66-81a569d18dca",
                            RoleId = "4"
                        },
                        new
                        {
                            UserId = "d2ae1474-9b71-457e-af0c-897b11ec41fe",
                            RoleId = "2"
                        },
                        new
                        {
                            UserId = "2c928c85-219d-4b81-8d83-0114828491d5",
                            RoleId = "3"
                        },
                        new
                        {
                            UserId = "dca4b91e-27f6-41da-b51b-1e4197664faa",
                            RoleId = "4"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("BeHealthy.Domain.Entities.Appointment", b =>
                {
                    b.HasOne("BeHealthy.Domain.Entities.Doctor", "Doctor")
                        .WithMany("Appointments")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BeHealthy.Domain.Entities.Nurse", "Nurse")
                        .WithMany("Appointments")
                        .HasForeignKey("NurseId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("BeHealthy.Domain.Entities.Patient", "Patient")
                        .WithMany("Appointments")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BeHealthy.Domain.Entities.Room", "Room")
                        .WithMany("Appointments")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Doctor");

                    b.Navigation("Nurse");

                    b.Navigation("Patient");

                    b.Navigation("Room");
                });

            modelBuilder.Entity("BeHealthy.Domain.Entities.Department", b =>
                {
                    b.HasOne("BeHealthy.Domain.Entities.Doctor", "HeadOfDepartment")
                        .WithMany()
                        .HasForeignKey("HeadOfDepartmentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("HeadOfDepartment");
                });

            modelBuilder.Entity("BeHealthy.Domain.Entities.Doctor", b =>
                {
                    b.HasOne("BeHealthy.Domain.Entities.Department", "Department")
                        .WithMany("Doctors")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("BeHealthy.Domain.Entities.Specialty", "Specialty")
                        .WithMany("Doctors")
                        .HasForeignKey("SpecialtyId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("BeHealthy.Domain.Entities.ApplicationUser", "User")
                        .WithOne("Doctor")
                        .HasForeignKey("BeHealthy.Domain.Entities.Doctor", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");

                    b.Navigation("Specialty");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BeHealthy.Domain.Entities.Nurse", b =>
                {
                    b.HasOne("BeHealthy.Domain.Entities.Department", "Department")
                        .WithMany("Nurses")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("BeHealthy.Domain.Entities.ApplicationUser", "User")
                        .WithOne("Nurse")
                        .HasForeignKey("BeHealthy.Domain.Entities.Nurse", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BeHealthy.Domain.Entities.Patient", b =>
                {
                    b.HasOne("BeHealthy.Domain.Entities.Department", "Department")
                        .WithMany("Patients")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("BeHealthy.Domain.Entities.ApplicationUser", "User")
                        .WithOne("Patient")
                        .HasForeignKey("BeHealthy.Domain.Entities.Patient", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BeHealthy.Domain.Entities.Prescription", b =>
                {
                    b.HasOne("BeHealthy.Domain.Entities.Doctor", "Doctor")
                        .WithMany()
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BeHealthy.Domain.Entities.Patient", "Patient")
                        .WithMany()
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Doctor");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("BeHealthy.Domain.Entities.Room", b =>
                {
                    b.HasOne("BeHealthy.Domain.Entities.Department", "Department")
                        .WithMany("Rooms")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("BeHealthy.Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("BeHealthy.Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BeHealthy.Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("BeHealthy.Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BeHealthy.Domain.Entities.ApplicationUser", b =>
                {
                    b.Navigation("Doctor");

                    b.Navigation("Nurse");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("BeHealthy.Domain.Entities.Department", b =>
                {
                    b.Navigation("Doctors");

                    b.Navigation("Nurses");

                    b.Navigation("Patients");

                    b.Navigation("Rooms");
                });

            modelBuilder.Entity("BeHealthy.Domain.Entities.Doctor", b =>
                {
                    b.Navigation("Appointments");
                });

            modelBuilder.Entity("BeHealthy.Domain.Entities.Nurse", b =>
                {
                    b.Navigation("Appointments");
                });

            modelBuilder.Entity("BeHealthy.Domain.Entities.Patient", b =>
                {
                    b.Navigation("Appointments");
                });

            modelBuilder.Entity("BeHealthy.Domain.Entities.Room", b =>
                {
                    b.Navigation("Appointments");
                });

            modelBuilder.Entity("BeHealthy.Domain.Entities.Specialty", b =>
                {
                    b.Navigation("Doctors");
                });
#pragma warning restore 612, 618
        }
    }
}
