@BeHealthy_HostAddress = https://localhost:7209
@controller = room
@id = 2

GET {{BeHealthy_HostAddress}}/api/{{controller}}

###

GET {{BeHealthy_HostAddress}}/api/{{controller}}/{{id}}

###

POST {{BeHealthy_HostAddress}}/api/{{controller}}
Content-Type: application/json

{
  "name": "Room",
  "number": "3",
  "department": "test"
}

###

PUT {{BeHealthy_HostAddress}}/api/{{controller}}/{id:int}?id=0
Content-Type: application/json

{
  
}

###

DELETE {{BeHealthy_HostAddress}}/api/{{controller}}/{id:int}?id=0

###
