<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>f53e0255-cd82-4941-9ee2-cdf30a606612</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Components\Pages\Roles\**" />
    <Compile Remove="Validators\**" />
    <Content Remove="Components\Pages\Roles\**" />
    <Content Remove="Validators\**" />
    <EmbeddedResource Remove="Components\Pages\Roles\**" />
    <EmbeddedResource Remove="Validators\**" />
    <None Remove="Components\Pages\Roles\**" />
    <None Remove="Validators\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Blazored.FluentValidation" Version="2.2.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.8">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="ChartJs.Blazor.Fork" Version="2.0.2" />
    <PackageReference Include="Microsoft.AspNetCore.Components.QuickGrid" Version="9.0.8" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.Server" Version="9.0.6" />
    <PackageReference Include="Microsoft.AspNetCore.Identity" Version="2.3.1" />
    <PackageReference Include="Microsoft.Extensions.Caching.Memory" Version="9.0.8" />
    <PackageReference Include="Microsoft.Extensions.Http.Resilience" Version="10.8.0" />
    <PackageReference Include="Microsoft.Extensions.Localization" Version="9.0.6" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="System.Security.Cryptography.Xml" Version="9.0.6" />
    <PackageReference Include="System.Text.Encodings.Web" Version="9.0.6" />
    <PackageReference Include="System.Text.Json" Version="9.0.8" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\BeHealthy.Shared\BeHealthy.Shared.csproj" />
  </ItemGroup>

</Project>
