services:
  behealthy:
    image: ${DOCKER_REGISTRY-}behealthy
    build:
      context: .
      dockerfile: BeHealthy/BeHealthy/Dockerfile
    ports:
      - "8000:8000"
      - "8001:8001"
    depends_on:
      - behealthydb

  behealthydb:
    image: postgres:latest
    container_name: behealthydb
    environment:
      - POSTGRES_DB=behealthy
      - POSTGRES_USER=behealthy_w1ur_user
      - POSTGRES_PASSWORD=MAAzUNXPSpDiGW7weNC3voseF8FL8zq2
    #volumes:
    # - ./.containers/behealthy-db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
