services:
  behealthy:
    image: ${DOCKER_REGISTRY-}behealthy
    container_name: behealthyapp
    build:
      context: .
      dockerfile: BeHealthy/BeHealthy/Dockerfile
    
  behealthydb:
    image: postgres:latest
    container_name: behealthydb
    environment:
      - POSTGRES_DB=behealthy
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=123456asd!@#
    ports:
      - "5432:5432"