<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Localization" Version="8.0.11" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Locales\Resource - Copy.Designer.cs">
      <DependentUpon>Resource - Copy.resx</DependentUpon>
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
    </Compile>
    <Compile Update="Locales\Resource.Designer.cs">
      <DependentUpon>Resource.resx</DependentUpon>
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Locales\Resource - Copy.resx">
      <LastGenOutput>Resource - Copy.Designer.cs</LastGenOutput>
      <Generator>PublicResXFileCodeGenerator</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Locales\Resource.en-US.resx">
      <Generator></Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Locales\Resource.resx">
      <LastGenOutput>Resource.Designer.cs</LastGenOutput>
      <Generator>PublicResXFileCodeGenerator</Generator>
    </EmbeddedResource>
  </ItemGroup>

</Project>
