<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Blazored.FluentValidation" Version="2.2.0" />
    <PackageReference Include="FluentValidation" Version="12.1.1" />
    <PackageReference Include="Microsoft.AspNetCore.Identity" Version="2.3.1" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="9.0.8" />
    <PackageReference Include="Microsoft.Extensions.Caching.Memory" Version="9.0.8" />
    <PackageReference Include="Microsoft.Extensions.Localization" Version="8.0.11" />
    <PackageReference Include="Scrutor" Version="6.1.0" />
    <PackageReference Include="System.Security.Cryptography.Xml" Version="8.0.2" />
    <PackageReference Include="System.Text.Encodings.Web" Version="8.0.0" />
    <PackageReference Include="System.Text.Json" Version="9.0.8" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\BeHealthy.Domain\BeHealthy.Domain.csproj" />
    <ProjectReference Include="..\BeHealthy.Shared\BeHealthy.Shared.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Features\Allergies\GetAllergyById\" />
    <Folder Include="Features\Allergies\CreateAllergy\" />
    <Folder Include="Features\Allergies\DeleteAllergy\" />
    <Folder Include="Features\Allergies\UpdateAllergy\" />
    <Folder Include="Features\Appointments\GetAppointments\" />
    <Folder Include="Features\Appointments\GetAppointmentReasonCounts\" />
    <Folder Include="Features\Appointments\GetAppointmentById\" />
    <Folder Include="Features\Appointments\CreateAppointment\" />
    <Folder Include="Features\Appointments\DeleteAppointment\" />
    <Folder Include="Features\Appointments\UpdateAppointment\" />
    <Folder Include="Features\AppSettings\" />
    <Folder Include="Features\Dashboard\" />
    <Folder Include="Features\Departments\GetDepartments\" />
    <Folder Include="Features\Departments\CreateDepartment\" />
    <Folder Include="Features\Departments\DeleteDepartment\" />
    <Folder Include="Features\Departments\UpdateDepartment\" />
    <Folder Include="Features\Doctors\GetDoctors\" />
    <Folder Include="Features\Doctors\GetDoctorsSimple\" />
    <Folder Include="Features\Doctors\GetDoctorAppointmentsByUserId\" />
    <Folder Include="Features\Doctors\GetDoctorPatients\" />
    <Folder Include="Features\Doctors\GetDoctorById\" />
    <Folder Include="Features\Doctors\CreateDoctor\" />
    <Folder Include="Features\Doctors\DeleteDoctor\" />
    <Folder Include="Features\Doctors\GetDoctorAppointments\" />
    <Folder Include="Features\MedicalRecords\GetMedicalRecords\" />
    <Folder Include="Features\MedicalRecords\GetMedicalRecordById\" />
    <Folder Include="Features\MedicalRecords\CreateMedicalRecord\" />
    <Folder Include="Features\MedicalRecords\DeleteNote\" />
    <Folder Include="Features\MedicalRecords\UpdateMedicalRecordNotes\" />
    <Folder Include="Features\Nurses\GetNurses\" />
    <Folder Include="Features\Nurses\GetNurseCount\" />
    <Folder Include="Features\Nurses\CreateNurse\" />
    <Folder Include="Features\Nurses\GetNursesSimple\" />
    <Folder Include="Features\Nurses\GetNurseById\" />
    <Folder Include="Features\Nurses\DeleteNurse\" />
    <Folder Include="Features\Nurses\UpdateNurse\" />
    <Folder Include="Features\Patients\GetPatientNurse\" />
    <Folder Include="Features\Patients\GetPatientAppointments\" />
    <Folder Include="Features\Patients\GetPatients\" />
    <Folder Include="Features\Patients\GetPatientById\" />
    <Folder Include="Features\Patients\GetPatientDoctors\" />
    <Folder Include="Features\Patients\CreatePatient\" />
    <Folder Include="Features\Patients\DeletePatient\" />
    <Folder Include="Features\Patients\GetPatientPrescription\" />
    <Folder Include="Features\Patients\GetPatientVisits\" />
    <Folder Include="Features\Patients\UpdatePatient\" />
    <Folder Include="Features\Prescriptions\GetPrescriptions\" />
    <Folder Include="Features\Prescriptions\GetPrescriptionById\" />
    <Folder Include="Features\Prescriptions\CreatePrescription\" />
    <Folder Include="Features\Prescriptions\DeletePrescription\" />
    <Folder Include="Features\Prescriptions\UpdatePrescription\" />
    <Folder Include="Features\Rooms\GetRooms\" />
    <Folder Include="Features\Rooms\GetRoomById\" />
    <Folder Include="Features\Rooms\CreateRoom\" />
    <Folder Include="Features\Rooms\DeleteRoom\" />
    <Folder Include="Features\Rooms\UpdateRoom\" />
    <Folder Include="Features\Seeding\GetEntityCounts\" />
    <Folder Include="Features\Seeding\SeedDoctors\" />
    <Folder Include="Features\Seeding\SeedPatients\" />
    <Folder Include="Features\Seeding\SeedNurses\" />
    <Folder Include="Features\Seeding\SeedAppointments\" />
    <Folder Include="Features\Seeding\SeedEntities\" />
    <Folder Include="Features\Specialties\GetSpecialties\" />
    <Folder Include="Features\Specialties\GetSpecialtyById\" />
    <Folder Include="Features\Specialties\CreateSpecialty\" />
    <Folder Include="Features\Specialties\DeleteSpecialty\" />
    <Folder Include="Features\Specialties\UpdateSpecialty\" />
    <Folder Include="Features\Visits\GetVisits\" />
    <Folder Include="Features\Visits\GetVisitById\" />
    <Folder Include="Features\Visits\GetVisitDiagnoses\" />
    <Folder Include="Features\Visits\GetVisitLabResults\" />
    <Folder Include="Features\Visits\CreateVisit\" />
    <Folder Include="Features\Visits\DeleteVisit\" />
    <Folder Include="Features\Visits\UpdateVisit\" />
    <Folder Include="Validations\Prescription\" />
  </ItemGroup>

</Project>
