<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Blazored.FluentValidation" Version="2.2.0" />
    <PackageReference Include="FluentValidation" Version="12.1.1" />
    <PackageReference Include="Microsoft.AspNetCore.Identity" Version="2.3.1" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="9.0.8" />
    <PackageReference Include="Microsoft.Extensions.Caching.Memory" Version="9.0.8" />
    <PackageReference Include="Microsoft.Extensions.Localization" Version="8.0.11" />
    <PackageReference Include="Scrutor" Version="6.1.0" />
    <PackageReference Include="System.Security.Cryptography.Xml" Version="8.0.2" />
    <PackageReference Include="System.Text.Encodings.Web" Version="8.0.0" />
    <PackageReference Include="System.Text.Json" Version="9.0.8" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\BeHealthy.Domain\BeHealthy.Domain.csproj" />
    <ProjectReference Include="..\BeHealthy.Shared\BeHealthy.Shared.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Features\Allergies\GetAllergyById\" />
    <Folder Include="Features\Allergies\CreateAllergy\" />
    <Folder Include="Features\Allergies\DeleteAllergy\" />
    <Folder Include="Features\Allergies\UpdateAllergy\" />
    <Folder Include="Features\Appointments\GetAppointments\" />
    <Folder Include="Features\Appointments\GetAppointmentReasonCounts\" />
    <Folder Include="Features\Appointments\GetAppointmentById\" />
    <Folder Include="Features\Appointments\CreateAppointment\" />
    <Folder Include="Features\Appointments\DeleteAppointment\" />
    <Folder Include="Features\Appointments\UpdateAppointment\" />
    <Folder Include="Features\AppSettings\" />
    <Folder Include="Features\Dashboard\" />
    <Folder Include="Features\Departments\GetDepartments\" />
    <Folder Include="Features\Departments\CreateDepartment\" />
    <Folder Include="Features\Departments\DeleteDepartment\" />
    <Folder Include="Features\Departments\UpdateDepartment\" />
    <Folder Include="Features\Doctors\GetDoctors\" />
    <Folder Include="Features\Doctors\GetDoctorsSimple\" />
    <Folder Include="Features\Doctors\GetDoctorAppointmentsByUserId\" />
    <Folder Include="Features\Doctors\GetDoctorPatients\" />
    <Folder Include="Features\Doctors\GetDoctorById\" />
    <Folder Include="Features\Doctors\CreateDoctor\" />
    <Folder Include="Features\Doctors\DeleteDoctor\" />
    <Folder Include="Features\Doctors\GetDoctorAppointments\" />
    <Folder Include="Features\MedicalRecords\" />
    <Folder Include="Features\Nurses\" />
    <Folder Include="Features\Patients\" />
    <Folder Include="Features\Prescriptions\" />
    <Folder Include="Features\Rooms\" />
    <Folder Include="Features\Seeding\" />
    <Folder Include="Features\Specialties\" />
    <Folder Include="Features\Visits\" />
    <Folder Include="Validations\Prescription\" />
  </ItemGroup>

</Project>
