name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch: # Allows manual re-runs

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Build Docker Image
        run: docker build -t vasillizantalis/behealthy:test2 -f BeHealthy/BeHealthy/Dockerfile .
      - name: Push Docker Image to Docker Hub
        run: |
          echo "${{ secrets.DOCKER_HUB_TOKEN }}" | docker login -u "${{ secrets.DOCKER_HUB_TOKEN }}" --password-stdin
          docker push vasillizantalis/behealthy:dev
