name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch: # Allows manual re-runs

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Build Docker Image
        run: |
          docker build -t vasillizantalis/behealthy:dev -f BeHealthy/BeHealthy/Dockerfile .

      - name: Verify Docker Image
        run: docker images | grep behealthy

      - name: Login to Docker Hub
        run: docker login -u "${{ secrets.DOCKER_USERNAME }}" -p ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Verify Docker Login
        run: docker info

      - name: Push Docker Image to Docker Hub
        run: |
          docker push vasillizantalis/behealthy:dev
