name: Run Scheduled PostgreSQL Procedure

on:
  #schedule:
    #- cron: "0 0 * * *"  # Runs daily at midnight UTC
  workflow_dispatch: # Allows manual execution

jobs:
  run-db-task:
    runs-on: ubuntu-latest
    steps:
      - name: Install PostgreSQL Client
        run: sudo apt-get install -y postgresql-client

      - name: Execute SQL Procedure
        run: |
          echo "Running MarkAppointmentsAsCompleted() procedure..."
          psql -h ${{ secrets.DB_HOST }} -U ${{ secrets.DB_USER }} -d ${{ secrets.DB_NAME }} -p ${{ secrets.DB_PORT }} -c "CALL public.MarkAppointmentsAsCompleted();"
          echo "Procedure executed successfully!"
        env:
          PGPASSWORD: ${{ secrets.DB_PASSWORD }}
