//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BeHealthy.Shared.Locales {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BeHealthy.Shared.Locales.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access Denied.
        /// </summary>
        public static string AccessDenied {
            get {
                return ResourceManager.GetString("AccessDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actions.
        /// </summary>
        public static string Actions {
            get {
                return ResourceManager.GetString("Actions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Row.
        /// </summary>
        public static string AddRow {
            get {
                return ResourceManager.GetString("AddRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An appointment already exists for doctor {0} from {1} to {2}. Please choose a different time.
        /// </summary>
        public static string AppointmentExistsForDoctor {
            get {
                return ResourceManager.GetString("AppointmentExistsForDoctor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An appointment already exists for nurse {0} from {1} to {2}.
        /// </summary>
        public static string AppointmentExistsForNurse {
            get {
                return ResourceManager.GetString("AppointmentExistsForNurse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An appointment already exists for patient {0} from {1} to {2}.
        /// </summary>
        public static string AppointmentExistsForPatient {
            get {
                return ResourceManager.GetString("AppointmentExistsForPatient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Follow Up.
        /// </summary>
        public static string AppointmentReason_FollowUp {
            get {
                return ResourceManager.GetString("AppointmentReason_FollowUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General Checkup.
        /// </summary>
        public static string AppointmentReason_GeneralCheckup {
            get {
                return ResourceManager.GetString("AppointmentReason_GeneralCheckup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Illness.
        /// </summary>
        public static string AppointmentReason_Illness {
            get {
                return ResourceManager.GetString("AppointmentReason_Illness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Injury.
        /// </summary>
        public static string AppointmentReason_Injury {
            get {
                return ResourceManager.GetString("AppointmentReason_Injury", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prescription.
        /// </summary>
        public static string AppointmentReason_Prescription {
            get {
                return ResourceManager.GetString("AppointmentReason_Prescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appointment Requires Room.
        /// </summary>
        public static string AppointmentRequiresRoom {
            get {
                return ResourceManager.GetString("AppointmentRequiresRoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appointments.
        /// </summary>
        public static string Appointments {
            get {
                return ResourceManager.GetString("Appointments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appointments by Reason.
        /// </summary>
        public static string AppointmentsByReason {
            get {
                return ResourceManager.GetString("AppointmentsByReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelled.
        /// </summary>
        public static string AppointmentStatus_Cancelled {
            get {
                return ResourceManager.GetString("AppointmentStatus_Cancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed.
        /// </summary>
        public static string AppointmentStatus_Completed {
            get {
                return ResourceManager.GetString("AppointmentStatus_Completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rescheduled.
        /// </summary>
        public static string AppointmentStatus_Rescheduled {
            get {
                return ResourceManager.GetString("AppointmentStatus_Rescheduled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scheduled.
        /// </summary>
        public static string AppointmentStatus_Scheduled {
            get {
                return ResourceManager.GetString("AppointmentStatus_Scheduled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to continue ?.
        /// </summary>
        public static string AreYouSureYouWantToContinue {
            get {
                return ResourceManager.GetString("AreYouSureYouWantToContinue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authorization.
        /// </summary>
        public static string Authorization {
            get {
                return ResourceManager.GetString("Authorization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to Dashboard.
        /// </summary>
        public static string BackToDashboard {
            get {
                return ResourceManager.GetString("BackToDashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card.
        /// </summary>
        public static string Card {
            get {
                return ResourceManager.GetString("Card", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration.
        /// </summary>
        public static string Configuration {
            get {
                return ResourceManager.GetString("Configuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConfirmDeletion.
        /// </summary>
        public static string ConfirmDeletion {
            get {
                return ResourceManager.GetString("ConfirmDeletion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Password.
        /// </summary>
        public static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created.
        /// </summary>
        public static string Created {
            get {
                return ResourceManager.GetString("Created", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new account.
        /// </summary>
        public static string CreateNewAccount {
            get {
                return ResourceManager.GetString("CreateNewAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard.
        /// </summary>
        public static string Dashboard {
            get {
                return ResourceManager.GetString("Dashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Prescribed.
        /// </summary>
        public static string DatePrescribed {
            get {
                return ResourceManager.GetString("DatePrescribed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department.
        /// </summary>
        public static string Department {
            get {
                return ResourceManager.GetString("Department", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Departments.
        /// </summary>
        public static string Departments {
            get {
                return ResourceManager.GetString("Departments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doctor.
        /// </summary>
        public static string Doctor {
            get {
                return ResourceManager.GetString("Doctor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doctors.
        /// </summary>
        public static string Doctors {
            get {
                return ResourceManager.GetString("Doctors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dosage.
        /// </summary>
        public static string Dosage {
            get {
                return ResourceManager.GetString("Dosage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration.
        /// </summary>
        public static string Duration {
            get {
                return ResourceManager.GetString("Duration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email is already used.
        /// </summary>
        public static string EmailAlreadyUsed {
            get {
                return ResourceManager.GetString("EmailAlreadyUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Time.
        /// </summary>
        public static string EndTime {
            get {
                return ResourceManager.GetString("EndTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Time cannot be earlier than Start Time.
        /// </summary>
        public static string EndTimeCannotBeEarlierThanStartTime {
            get {
                return ResourceManager.GetString("EndTimeCannotBeEarlierThanStartTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filters.
        /// </summary>
        public static string Filters {
            get {
                return ResourceManager.GetString("Filters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        public static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string FullName {
            get {
                return ResourceManager.GetString("FullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GeneralData.
        /// </summary>
        public static string GeneralData {
            get {
                return ResourceManager.GetString("GeneralData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Greek.
        /// </summary>
        public static string Greek {
            get {
                return ResourceManager.GetString("Greek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grid.
        /// </summary>
        public static string Grid {
            get {
                return ResourceManager.GetString("Grid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Head of Department.
        /// </summary>
        public static string HeadΟfDepartment {
            get {
                return ResourceManager.GetString("HeadΟfDepartment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello.
        /// </summary>
        public static string Hello {
            get {
                return ResourceManager.GetString("Hello", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hour.
        /// </summary>
        public static string Hour {
            get {
                return ResourceManager.GetString("Hour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Email.
        /// </summary>
        public static string InvalidEmail {
            get {
                return ResourceManager.GetString("InvalidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Email Format.
        /// </summary>
        public static string InvalidEmailFormat {
            get {
                return ResourceManager.GetString("InvalidEmailFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Login Credentials.
        /// </summary>
        public static string InvalidLoginCredentials {
            get {
                return ResourceManager.GetString("InvalidLoginCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Username.
        /// </summary>
        public static string InvalidUserName {
            get {
                return ResourceManager.GetString("InvalidUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Joined.
        /// </summary>
        public static string Joined {
            get {
                return ResourceManager.GetString("Joined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string LanguageOptions_English {
            get {
                return ResourceManager.GetString("LanguageOptions_English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Greek.
        /// </summary>
        public static string LanguageOptions_Greek {
            get {
                return ResourceManager.GetString("LanguageOptions_Greek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        public static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        public static string Location {
            get {
                return ResourceManager.GetString("Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login with your Credentials.
        /// </summary>
        public static string LoginWithYourCredentials {
            get {
                return ResourceManager.GetString("LoginWithYourCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Management.
        /// </summary>
        public static string Management {
            get {
                return ResourceManager.GetString("Management", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mass Import.
        /// </summary>
        public static string MassImport {
            get {
                return ResourceManager.GetString("MassImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medication.
        /// </summary>
        public static string Medication {
            get {
                return ResourceManager.GetString("Medication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minutes.
        /// </summary>
        public static string Minutes {
            get {
                return ResourceManager.GetString("Minutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must be between {1} - {2}.
        /// </summary>
        public static string MustBeBetween {
            get {
                return ResourceManager.GetString("MustBeBetween", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Available {0}.
        /// </summary>
        public static string NoAvailable {
            get {
                return ResourceManager.GetString("NoAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Available.
        /// </summary>
        public static string NotAvailable {
            get {
                return ResourceManager.GetString("NotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes.
        /// </summary>
        public static string Notes {
            get {
                return ResourceManager.GetString("Notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Found.
        /// </summary>
        public static string NotFound {
            get {
                return ResourceManager.GetString("NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No {0} Joined Lately.
        /// </summary>
        public static string NoUsersJoinedLately {
            get {
                return ResourceManager.GetString("NoUsersJoinedLately", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number.
        /// </summary>
        public static string Number {
            get {
                return ResourceManager.GetString("Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of Appointments.
        /// </summary>
        public static string NumberOfAppointments {
            get {
                return ResourceManager.GetString("NumberOfAppointments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nurse.
        /// </summary>
        public static string Nurse {
            get {
                return ResourceManager.GetString("Nurse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nurses.
        /// </summary>
        public static string Nurses {
            get {
                return ResourceManager.GetString("Nurses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must have at least one digit.
        /// </summary>
        public static string PasswordNeedsDigit {
            get {
                return ResourceManager.GetString("PasswordNeedsDigit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must have at least one lowercase.
        /// </summary>
        public static string PasswordNeedsLowercase {
            get {
                return ResourceManager.GetString("PasswordNeedsLowercase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must have at least one non alphanumeric character.
        /// </summary>
        public static string PasswordNeedsNonAlphanumericCharacter {
            get {
                return ResourceManager.GetString("PasswordNeedsNonAlphanumericCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must have at least one uppercase.
        /// </summary>
        public static string PasswordNeedsUppercase {
            get {
                return ResourceManager.GetString("PasswordNeedsUppercase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwords do not match.
        /// </summary>
        public static string PasswordsDoNotMatch {
            get {
                return ResourceManager.GetString("PasswordsDoNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Password must be at least {0} characters.
        /// </summary>
        public static string PasswordTooShort {
            get {
                return ResourceManager.GetString("PasswordTooShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patient.
        /// </summary>
        public static string Patient {
            get {
                return ResourceManager.GetString("Patient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patients.
        /// </summary>
        public static string Patients {
            get {
                return ResourceManager.GetString("Patients", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Number.
        /// </summary>
        public static string PhoneNumber {
            get {
                return ResourceManager.GetString("PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Select.
        /// </summary>
        public static string PleaseSelect {
            get {
                return ResourceManager.GetString("PleaseSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prescription.
        /// </summary>
        public static string Prescription {
            get {
                return ResourceManager.GetString("Prescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prescriptions.
        /// </summary>
        public static string Prescriptions {
            get {
                return ResourceManager.GetString("Prescriptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privilege.
        /// </summary>
        public static string Privilege {
            get {
                return ResourceManager.GetString("Privilege", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Appointments.
        /// </summary>
        public static string PrivilegeName_DeleteAppointments {
            get {
                return ResourceManager.GetString("PrivilegeName_DeleteAppointments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Patient.
        /// </summary>
        public static string PrivilegeName_DeletePatient {
            get {
                return ResourceManager.GetString("PrivilegeName_DeletePatient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Appointments.
        /// </summary>
        public static string PrivilegeName_EditAppointments {
            get {
                return ResourceManager.GetString("PrivilegeName_EditAppointments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Patient.
        /// </summary>
        public static string PrivilegeName_EditPatient {
            get {
                return ResourceManager.GetString("PrivilegeName_EditPatient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate Medical Reports.
        /// </summary>
        public static string PrivilegeName_GenerateMedicalReports {
            get {
                return ResourceManager.GetString("PrivilegeName_GenerateMedicalReports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prescribe medications.
        /// </summary>
        public static string PrivilegeName_PrescribeMedications {
            get {
                return ResourceManager.GetString("PrivilegeName_PrescribeMedications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Patient Prescriptions.
        /// </summary>
        public static string PrivilegeName_ViewPatientPrescriptions {
            get {
                return ResourceManager.GetString("PrivilegeName_ViewPatientPrescriptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privileges.
        /// </summary>
        public static string Privileges {
            get {
                return ResourceManager.GetString("Privileges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        public static string Profile {
            get {
                return ResourceManager.GetString("Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} invalid format.
        /// </summary>
        public static string PropertyInvalidFormat {
            get {
                return ResourceManager.GetString("PropertyInvalidFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} should have at least {1} characters..
        /// </summary>
        public static string PropertyMinimumCharacters {
            get {
                return ResourceManager.GetString("PropertyMinimumCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is required.
        /// </summary>
        public static string PropertyRequired {
            get {
                return ResourceManager.GetString("PropertyRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reason.
        /// </summary>
        public static string Reason {
            get {
                return ResourceManager.GetString("Reason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reason for Appointment.
        /// </summary>
        public static string ReasonOfAppoinment {
            get {
                return ResourceManager.GetString("ReasonOfAppoinment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recently Added Patients.
        /// </summary>
        public static string RecentlyAddedPatients {
            get {
                return ResourceManager.GetString("RecentlyAddedPatients", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember me.
        /// </summary>
        public static string RememberMe {
            get {
                return ResourceManager.GetString("RememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required.
        /// </summary>
        public static string Required {
            get {
                return ResourceManager.GetString("Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role.
        /// </summary>
        public static string Role {
            get {
                return ResourceManager.GetString("Role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Room.
        /// </summary>
        public static string Room {
            get {
                return ResourceManager.GetString("Room", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Room is booked at that time.
        /// </summary>
        public static string RoomIsBookedAtThatTime {
            get {
                return ResourceManager.GetString("RoomIsBookedAtThatTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rooms.
        /// </summary>
        public static string Rooms {
            get {
                return ResourceManager.GetString("Rooms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong.
        /// </summary>
        public static string SomethingWentWrong {
            get {
                return ResourceManager.GetString("SomethingWentWrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specialties.
        /// </summary>
        public static string Specialties {
            get {
                return ResourceManager.GetString("Specialties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specialty.
        /// </summary>
        public static string Specialty {
            get {
                return ResourceManager.GetString("Specialty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Time.
        /// </summary>
        public static string StartTime {
            get {
                return ResourceManager.GetString("StartTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        public static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field {0} is required.
        /// </summary>
        public static string TheFieldIsRequired {
            get {
                return ResourceManager.GetString("TheFieldIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no {0}.
        /// </summary>
        public static string ThereAreNo {
            get {
                return ResourceManager.GetString("ThereAreNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This action cannot be undone.
        /// </summary>
        public static string ThisActionCannotBeUndone {
            get {
                return ResourceManager.GetString("ThisActionCannotBeUndone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Appointments.
        /// </summary>
        public static string TotalAppointments {
            get {
                return ResourceManager.GetString("TotalAppointments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unauthorized.
        /// </summary>
        public static string Unauthorized {
            get {
                return ResourceManager.GetString("Unauthorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upcoming Appointments.
        /// </summary>
        public static string UpcomingAppointments {
            get {
                return ResourceManager.GetString("UpcomingAppointments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Distribution.
        /// </summary>
        public static string UserDistribution {
            get {
                return ResourceManager.GetString("UserDistribution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin.
        /// </summary>
        public static string UserRole_Admin {
            get {
                return ResourceManager.GetString("UserRole_Admin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doctor.
        /// </summary>
        public static string UserRole_Doctor {
            get {
                return ResourceManager.GetString("UserRole_Doctor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nurse.
        /// </summary>
        public static string UserRole_Nurse {
            get {
                return ResourceManager.GetString("UserRole_Nurse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patient.
        /// </summary>
        public static string UserRole_Patient {
            get {
                return ResourceManager.GetString("UserRole_Patient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are not authorized to access this page.
        /// </summary>
        public static string YouAreNotAuthorizedToAccessPage {
            get {
                return ResourceManager.GetString("YouAreNotAuthorizedToAccessPage", resourceCulture);
            }
        }
    }
}
